## Read in Oscar CSV back into Dataframe

In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
oscars_df = pd.read_csv('oscar_movies.csv')

In [3]:
oscars_df.describe()

        Unnamed: 0  metacritic score        budget
count  1990.000000       1532.000000  1.287000e+03
mean    994.500000         72.720627  4.023991e+07
std     574.607837         12.891813  4.768131e+07
min       0.000000         25.000000  6.000000e+04
25%     497.250000         65.000000  1.100000e+07
50%     994.500000         74.000000  2.400000e+07
75%    1491.750000         82.000000  4.700000e+07
max    1989.000000        100.000000  3.210000e+08

In [4]:
oscars_df.drop(columns = ['Unnamed: 0'],inplace=True)

In [5]:
oscars_df.shape

(1990, 14)

In [6]:
oscars_df.tail()

,IMDBId,movie title,director(s),writer(s),casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany
1985,NaN,Tuba Atlantic,['Hallvar Witzø'],['Linn-Jeanethe Kyed'],"['Edvard Hægstad', 'Ingrid Viken', 'Terje Ranes']","['Short', 'Comedy', 'Drama']",Norwegian,Norway,25min,TV-MA,Jun-10,NaN,NaN,NaN
1986,NaN,The Lion King,['Jon Favreau'],"['Jeff Nathanson', 'Irene Mecchi', '2 more cre...","['Donald Glover', 'Beyoncé', 'Seth Rogen']","['Animation', 'Adventure', 'Drama', 'Family', ...",English,USA,1h 58min,PG,19-Jul-19,55.0,260000000.0,Walt Disney Studios Motion Pictures
1987,NaN,Ford v Ferrari,['James Mangold'],"['Jez Butterworth', 'John-Henry Butterworth', ...","['Matt Damon', 'Christian Bale', 'Jon Bernthal']","['Action', 'Biography', 'Drama', 'Sport']",English,USA,2h 32min,PG-13,15-Nov-19,81.0,97600000.0,Twentieth Century Fox
1988,NaN,Common Threads: Stories from the Quilt,"['Rob Epstein', 'Jeffrey Friedman']","['Rob Epstein', 'Jeffrey Friedman', '1 more cr...","['Sara Lewinstein', 'David Mandell', 'Suzi Man...","['Documentary', 'Biography', 'History']",English,USA,1h 19min,1h 19min,NaN,NaN,NaN,Direct Cinema Limited
1989,NaN,Wyatt Earp,['Lawrence Kasdan'],"['Dan Gordon', 'Lawrence Kasdan']","['Kevin Costner', 'Dennis Quaid', 'Gene Hackman']","['Adventure', 'Biography', 'Crime', 'Drama', '...",English,USA,3h 11min,PG-13,24-Jun-94,47.0,63000000.0,Warner Bros.

In [7]:
oscars_df.to_csv('oscar_moviesBackup.csv',encoding='utf-8-sig')

In [8]:
oscars_df.head()

,IMDBId,movie title,director(s),writer(s),casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany
0,tt0091763,Platoon,['Oliver Stone'],['Oliver Stone'],"['Charlie Sheen', 'Tom Berenger', 'Willem Dafoe']","['Drama', 'War']",English,USA,2h,R,6-Feb-87,92.0,6000000.0,Orion Pictures
1,tt0082979,Reds,['Warren Beatty'],"['Warren Beatty', 'Trevor Griffiths']","['Warren Beatty', 'Diane Keaton', 'Edward Herr...","['Biography', 'Drama', 'History', 'Romance']",English,USA,3h 15min,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures
2,tt0084434,An Officer and a Gentleman,['Taylor Hackford'],['Douglas Day Stewart'],"['Richard Gere', 'Debra Winger', 'David Keith']","['Drama', 'Romance']",English,USA,2h 4min,R,13-Aug-82,75.0,7500000.0,Paramount Pictures
3,tt0119360,In & Out,['Frank Oz'],['Paul Rudnick'],"['Kevin Kline', 'Joan Cusack', 'Tom Selleck']","['Comedy', 'Romance']",English,USA,1h 30min,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures
4,tt0292542,Son of the Bride,['Juan José Campanella'],"['Juan José Campanella', 'Fernando Castets']","['Ricardo Darín', 'Héctor Alterio', 'Norma Ale...","['Comedy', 'Drama']",Spanish,Argentina,2h 3min,R,16-Aug-01,68.0,NaN,Sony Pictures Classics

In [9]:
oscars_df.shape

(1990, 14)

In [10]:
def clean_columns(column):
    oscars_df[column] = oscars_df[column].str.strip('[]').astype(str)
    return oscars_df

In [11]:
def remove_quotation(column):
    oscars_df[column]= oscars_df[column].str.strip()
    oscars_df[column]= oscars_df[column].str.strip("''")
    oscars_df[column]= oscars_df[column].str.strip("'")
    return oscars_df

In [12]:
clean_columns('writer(s)')
clean_columns('director(s)')
clean_columns('casts')
clean_columns('genre(s)')

,IMDBId,movie title,director(s),writer(s),casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany
0,tt0091763,Platoon,'Oliver Stone','Oliver Stone',"'Charlie Sheen', 'Tom Berenger', 'Willem Dafoe'","'Drama', 'War'",English,USA,2h,R,6-Feb-87,92.0,6000000.0,Orion Pictures
1,tt0082979,Reds,'Warren Beatty',"'Warren Beatty', 'Trevor Griffiths'","'Warren Beatty', 'Diane Keaton', 'Edward Herrm...","'Biography', 'Drama', 'History', 'Romance'",English,USA,3h 15min,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures
2,tt0084434,An Officer and a Gentleman,'Taylor Hackford','Douglas Day Stewart',"'Richard Gere', 'Debra Winger', 'David Keith'","'Drama', 'Romance'",English,USA,2h 4min,R,13-Aug-82,75.0,7500000.0,Paramount Pictures
3,tt0119360,In & Out,'Frank Oz','Paul Rudnick',"'Kevin Kline', 'Joan Cusack', 'Tom Selleck'","'Comedy', 'Romance'",English,USA,1h 30min,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures
4,tt0292542,Son of the Bride,'Juan José Campanella',"'Juan José Campanella', 'Fernando Castets'","'Ricardo Darín', 'Héctor Alterio', 'Norma Alea...","'Comedy', 'Drama'",Spanish,Argentina,2h 3min,R,16-Aug-01,68.0,NaN,Sony Pictures Classics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,NaN,Tuba Atlantic,'Hallvar Witzø','Linn-Jeanethe Kyed',"'Edvard Hægstad', 'Ingrid Viken', 'Terje Ranes'","'Short', 'Comedy', 'Drama'",Norwegian,Norway,25min,TV-MA,Jun-10,NaN,NaN,NaN
1986,NaN,The Lion King,'Jon Favreau',"'Jeff Nathanson', 'Irene Mecchi', '2 more cred...","'Donald Glover', 'Beyoncé', 'Seth Rogen'","'Animation', 'Adventure', 'Drama', 'Family', '...",English,USA,1h 58min,PG,19-Jul-19,55.0,260000000.0,Walt Disney Studios Motion Pictures
1987,NaN,Ford v Ferrari,'James Mangold',"'Jez Butterworth', 'John-Henry Butterworth', '...","'Matt Damon', 'Christian Bale', 'Jon Bernthal'","'Action', 'Biography', 'Drama', 'Sport'",English,USA,2h 32min,PG-13,15-Nov-19,81.0,97600000.0,Twentieth Century Fox
1988,NaN,Common Threads: Stories from the Quilt,"'Rob Epstein', 'Jeffrey Friedman'","'Rob Epstein', 'Jeffrey Friedman', '1 more cre...","'Sara Lewinstein', 'David Mandell', 'Suzi Mand...","'Documentary', 'Biography', 'History'",English,USA,1h 19min,1h 19min,NaN,NaN,NaN,Direct Cinema Limited
1989,NaN,Wyatt Earp,'Lawrence Kasdan',"'Dan Gordon', 'Lawrence Kasdan'","'Kevin Costner', 'Dennis Quaid', 'Gene Hackman'","'Adventure', 'Biography', 'Crime', 'Drama', 'W...",English,USA,3h 11min,PG-13,24-Jun-94,47.0,63000000.0,Warner Bros.

In [13]:
oscars_df.head()

,IMDBId,movie title,director(s),writer(s),casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany
0,tt0091763,Platoon,'Oliver Stone','Oliver Stone',"'Charlie Sheen', 'Tom Berenger', 'Willem Dafoe'","'Drama', 'War'",English,USA,2h,R,6-Feb-87,92.0,6000000.0,Orion Pictures
1,tt0082979,Reds,'Warren Beatty',"'Warren Beatty', 'Trevor Griffiths'","'Warren Beatty', 'Diane Keaton', 'Edward Herrm...","'Biography', 'Drama', 'History', 'Romance'",English,USA,3h 15min,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures
2,tt0084434,An Officer and a Gentleman,'Taylor Hackford','Douglas Day Stewart',"'Richard Gere', 'Debra Winger', 'David Keith'","'Drama', 'Romance'",English,USA,2h 4min,R,13-Aug-82,75.0,7500000.0,Paramount Pictures
3,tt0119360,In & Out,'Frank Oz','Paul Rudnick',"'Kevin Kline', 'Joan Cusack', 'Tom Selleck'","'Comedy', 'Romance'",English,USA,1h 30min,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures
4,tt0292542,Son of the Bride,'Juan José Campanella',"'Juan José Campanella', 'Fernando Castets'","'Ricardo Darín', 'Héctor Alterio', 'Norma Alea...","'Comedy', 'Drama'",Spanish,Argentina,2h 3min,R,16-Aug-01,68.0,NaN,Sony Pictures Classics

Split the writers columns and explore how many writers are in each new column

In [14]:
oscars_df[['writer1','writer2','writer3']] = oscars_df['writer(s)'].apply(lambda x: pd.Series(x.split(',')))

In [15]:
oscars_df.tail()

,IMDBId,movie title,director(s),writer(s),casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany,writer1,writer2,writer3
1985,NaN,Tuba Atlantic,'Hallvar Witzø','Linn-Jeanethe Kyed',"'Edvard Hægstad', 'Ingrid Viken', 'Terje Ranes'","'Short', 'Comedy', 'Drama'",Norwegian,Norway,25min,TV-MA,Jun-10,NaN,NaN,NaN,'Linn-Jeanethe Kyed',NaN,NaN
1986,NaN,The Lion King,'Jon Favreau',"'Jeff Nathanson', 'Irene Mecchi', '2 more cred...","'Donald Glover', 'Beyoncé', 'Seth Rogen'","'Animation', 'Adventure', 'Drama', 'Family', '...",English,USA,1h 58min,PG,19-Jul-19,55.0,260000000.0,Walt Disney Studios Motion Pictures,'Jeff Nathanson','Irene Mecchi','2 more credits'
1987,NaN,Ford v Ferrari,'James Mangold',"'Jez Butterworth', 'John-Henry Butterworth', '...","'Matt Damon', 'Christian Bale', 'Jon Bernthal'","'Action', 'Biography', 'Drama', 'Sport'",English,USA,2h 32min,PG-13,15-Nov-19,81.0,97600000.0,Twentieth Century Fox,'Jez Butterworth','John-Henry Butterworth','1 more credit'
1988,NaN,Common Threads: Stories from the Quilt,"'Rob Epstein', 'Jeffrey Friedman'","'Rob Epstein', 'Jeffrey Friedman', '1 more cre...","'Sara Lewinstein', 'David Mandell', 'Suzi Mand...","'Documentary', 'Biography', 'History'",English,USA,1h 19min,1h 19min,NaN,NaN,NaN,Direct Cinema Limited,'Rob Epstein','Jeffrey Friedman','1 more credit'
1989,NaN,Wyatt Earp,'Lawrence Kasdan',"'Dan Gordon', 'Lawrence Kasdan'","'Kevin Costner', 'Dennis Quaid', 'Gene Hackman'","'Adventure', 'Biography', 'Crime', 'Drama', 'W...",English,USA,3h 11min,PG-13,24-Jun-94,47.0,63000000.0,Warner Bros.,'Dan Gordon','Lawrence Kasdan',NaN

In [16]:
#Writers one should have the same number of writers as length of data frame
oscars_df['writer1'].count()

1990

In [17]:
#Writers 2 should have less
oscars_df['writer2'].count()

1425

In [18]:
#Writers 3 should have less
oscars_df['writer3'].count()

754

In [19]:
oscars_df['writer3'].value_counts()

 '1 more credit'      368
 '2 more credits'     199
 '3 more credits'     100
 '4 more credits'      34
 '6 more credits'      15
 '5 more credits'      13
 '7 more credits'       7
 '9 more credits'       4
 '24 more credits'      4
 '8 more credits'       3
 '18 more credits'      2
 '14 more credits'      2
 '27 more credits'      2
 '23 more credits'      1
Name: writer3, dtype: int64

### The third writers column is not telling us who wrote for the movie so that column will be dropped

In [20]:
oscars_df.drop(['writer(s)','writer3'], axis=1,inplace=True)

In [21]:
remove_quotation('writer1')
remove_quotation('writer2')

,IMDBId,movie title,director(s),casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany,writer1,writer2
0,tt0091763,Platoon,'Oliver Stone',"'Charlie Sheen', 'Tom Berenger', 'Willem Dafoe'","'Drama', 'War'",English,USA,2h,R,6-Feb-87,92.0,6000000.0,Orion Pictures,Oliver Stone,NaN
1,tt0082979,Reds,'Warren Beatty',"'Warren Beatty', 'Diane Keaton', 'Edward Herrm...","'Biography', 'Drama', 'History', 'Romance'",English,USA,3h 15min,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures,Warren Beatty,Trevor Griffiths
2,tt0084434,An Officer and a Gentleman,'Taylor Hackford',"'Richard Gere', 'Debra Winger', 'David Keith'","'Drama', 'Romance'",English,USA,2h 4min,R,13-Aug-82,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,NaN
3,tt0119360,In & Out,'Frank Oz',"'Kevin Kline', 'Joan Cusack', 'Tom Selleck'","'Comedy', 'Romance'",English,USA,1h 30min,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures,Paul Rudnick,NaN
4,tt0292542,Son of the Bride,'Juan José Campanella',"'Ricardo Darín', 'Héctor Alterio', 'Norma Alea...","'Comedy', 'Drama'",Spanish,Argentina,2h 3min,R,16-Aug-01,68.0,NaN,Sony Pictures Classics,Juan José Campanella,Fernando Castets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,NaN,Tuba Atlantic,'Hallvar Witzø',"'Edvard Hægstad', 'Ingrid Viken', 'Terje Ranes'","'Short', 'Comedy', 'Drama'",Norwegian,Norway,25min,TV-MA,Jun-10,NaN,NaN,NaN,Linn-Jeanethe Kyed,NaN
1986,NaN,The Lion King,'Jon Favreau',"'Donald Glover', 'Beyoncé', 'Seth Rogen'","'Animation', 'Adventure', 'Drama', 'Family', '...",English,USA,1h 58min,PG,19-Jul-19,55.0,260000000.0,Walt Disney Studios Motion Pictures,Jeff Nathanson,Irene Mecchi
1987,NaN,Ford v Ferrari,'James Mangold',"'Matt Damon', 'Christian Bale', 'Jon Bernthal'","'Action', 'Biography', 'Drama', 'Sport'",English,USA,2h 32min,PG-13,15-Nov-19,81.0,97600000.0,Twentieth Century Fox,Jez Butterworth,John-Henry Butterworth
1988,NaN,Common Threads: Stories from the Quilt,"'Rob Epstein', 'Jeffrey Friedman'","'Sara Lewinstein', 'David Mandell', 'Suzi Mand...","'Documentary', 'Biography', 'History'",English,USA,1h 19min,1h 19min,NaN,NaN,NaN,Direct Cinema Limited,Rob Epstein,Jeffrey Friedman
1989,NaN,Wyatt Earp,'Lawrence Kasdan',"'Kevin Costner', 'Dennis Quaid', 'Gene Hackman'","'Adventure', 'Biography', 'Crime', 'Drama', 'W...",English,USA,3h 11min,PG-13,24-Jun-94,47.0,63000000.0,Warner Bros.,Dan Gordon,Lawrence Kasdan

### Now I will split and explore directors

In [22]:
oscars_df[['director1','director2','director3']] = oscars_df['director(s)'].apply(lambda x: pd.Series(x.split(',')))

In [23]:
oscars_df['director1'].count()

1990

In [24]:
oscars_df['director2'].count()

135

In [25]:
oscars_df['director2'].value_counts()

 'Joel Coen'            7
 'John Musker'          6
 'Ethan Coen'           5
 'Joe Russo'            3
 'Kirk Wise'            3
                       ..
 'Vicky Jenson'         1
 'Javier Mariscal'      1
 'Ljubomir Stefanov'    1
 'Barna Kabay'          1
 'Will Speck'           1
Name: director2, Length: 73, dtype: int64

In [26]:
oscars_df['director3'].count()

14

#### With the count of directors being so low I will drop the column and rename directors 1 to director

In [27]:
oscars_df.drop(['director(s)','director2','director3'], axis=1,inplace=True)

In [28]:
oscars_df.head()

,IMDBId,movie title,casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany,writer1,writer2,director1
0,tt0091763,Platoon,"'Charlie Sheen', 'Tom Berenger', 'Willem Dafoe'","'Drama', 'War'",English,USA,2h,R,6-Feb-87,92.0,6000000.0,Orion Pictures,Oliver Stone,NaN,'Oliver Stone'
1,tt0082979,Reds,"'Warren Beatty', 'Diane Keaton', 'Edward Herrm...","'Biography', 'Drama', 'History', 'Romance'",English,USA,3h 15min,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures,Warren Beatty,Trevor Griffiths,'Warren Beatty'
2,tt0084434,An Officer and a Gentleman,"'Richard Gere', 'Debra Winger', 'David Keith'","'Drama', 'Romance'",English,USA,2h 4min,R,13-Aug-82,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,NaN,'Taylor Hackford'
3,tt0119360,In & Out,"'Kevin Kline', 'Joan Cusack', 'Tom Selleck'","'Comedy', 'Romance'",English,USA,1h 30min,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures,Paul Rudnick,NaN,'Frank Oz'
4,tt0292542,Son of the Bride,"'Ricardo Darín', 'Héctor Alterio', 'Norma Alea...","'Comedy', 'Drama'",Spanish,Argentina,2h 3min,R,16-Aug-01,68.0,NaN,Sony Pictures Classics,Juan José Campanella,Fernando Castets,'Juan José Campanella'

In [29]:
oscars_df.rename(columns={"director1": "director"},inplace=True)

In [30]:
remove_quotation('director')

,IMDBId,movie title,casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany,writer1,writer2,director
0,tt0091763,Platoon,"'Charlie Sheen', 'Tom Berenger', 'Willem Dafoe'","'Drama', 'War'",English,USA,2h,R,6-Feb-87,92.0,6000000.0,Orion Pictures,Oliver Stone,NaN,Oliver Stone
1,tt0082979,Reds,"'Warren Beatty', 'Diane Keaton', 'Edward Herrm...","'Biography', 'Drama', 'History', 'Romance'",English,USA,3h 15min,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures,Warren Beatty,Trevor Griffiths,Warren Beatty
2,tt0084434,An Officer and a Gentleman,"'Richard Gere', 'Debra Winger', 'David Keith'","'Drama', 'Romance'",English,USA,2h 4min,R,13-Aug-82,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,NaN,Taylor Hackford
3,tt0119360,In & Out,"'Kevin Kline', 'Joan Cusack', 'Tom Selleck'","'Comedy', 'Romance'",English,USA,1h 30min,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures,Paul Rudnick,NaN,Frank Oz
4,tt0292542,Son of the Bride,"'Ricardo Darín', 'Héctor Alterio', 'Norma Alea...","'Comedy', 'Drama'",Spanish,Argentina,2h 3min,R,16-Aug-01,68.0,NaN,Sony Pictures Classics,Juan José Campanella,Fernando Castets,Juan José Campanella
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,NaN,Tuba Atlantic,"'Edvard Hægstad', 'Ingrid Viken', 'Terje Ranes'","'Short', 'Comedy', 'Drama'",Norwegian,Norway,25min,TV-MA,Jun-10,NaN,NaN,NaN,Linn-Jeanethe Kyed,NaN,Hallvar Witzø
1986,NaN,The Lion King,"'Donald Glover', 'Beyoncé', 'Seth Rogen'","'Animation', 'Adventure', 'Drama', 'Family', '...",English,USA,1h 58min,PG,19-Jul-19,55.0,260000000.0,Walt Disney Studios Motion Pictures,Jeff Nathanson,Irene Mecchi,Jon Favreau
1987,NaN,Ford v Ferrari,"'Matt Damon', 'Christian Bale', 'Jon Bernthal'","'Action', 'Biography', 'Drama', 'Sport'",English,USA,2h 32min,PG-13,15-Nov-19,81.0,97600000.0,Twentieth Century Fox,Jez Butterworth,John-Henry Butterworth,James Mangold
1988,NaN,Common Threads: Stories from the Quilt,"'Sara Lewinstein', 'David Mandell', 'Suzi Mand...","'Documentary', 'Biography', 'History'",English,USA,1h 19min,1h 19min,NaN,NaN,NaN,Direct Cinema Limited,Rob Epstein,Jeffrey Friedman,Rob Epstein
1989,NaN,Wyatt Earp,"'Kevin Costner', 'Dennis Quaid', 'Gene Hackman'","'Adventure', 'Biography', 'Crime', 'Drama', 'W...",English,USA,3h 11min,PG-13,24-Jun-94,47.0,63000000.0,Warner Bros.,Dan Gordon,Lawrence Kasdan,Lawrence Kasdan

In [31]:
oscars_df['director']

0               Oliver Stone
1              Warren Beatty
2            Taylor Hackford
3                   Frank Oz
4       Juan José Campanella
                ...
1985           Hallvar Witzø
1986             Jon Favreau
1987           James Mangold
1988             Rob Epstein
1989         Lawrence Kasdan
Name: director, Length: 1990, dtype: object

#### I will now explore split the cast and explore

In [32]:
oscars_df.casts.value_counts()

'William Shatner', 'Leonard Nimoy', 'DeForest Kelley'                 5
'Hayden Christensen', 'Natalie Portman', 'Ewan McGregor'              4
'Daniel Radcliffe', 'Emma Watson', 'Rupert Grint'                     4
'Dean-Charles Chapman', 'George MacKay', 'Daniel Mays'                3
'Mathieu Amalric', 'Emmanuelle Seigner', 'Marie-Josée Croze'          3
                                                                     ..
'Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'                  1
'Gabourey Sidibe', "Mo'Nique", 'Paula Patton'                         1
'Megan Follows', 'David Fox', 'Clare Coulter'                         1
'Armin Mueller-Stahl', 'Elisabeth Trissenaar', 'Wojciech Pszoniak'    1
'Philippe Noiret', 'Michele Placido', 'Vittorio Mezzogiorno'          1
Name: casts, Length: 1255, dtype: int64

In [33]:
oscars_df[['Lead_Actor','Supporting_Actor_1','Supporting_Actor_2']] = oscars_df['casts'].apply(lambda x: pd.Series(x.split(',')))

In [34]:
oscars_df['Lead_Actor'].value_counts()

'Tom Hanks'            23
'Meryl Streep'         22
'Leonardo DiCaprio'    20
'Jeff Bridges'         17
'Denzel Washington'    15
                       ..
'Mungau Dain'           1
'Shia LaBeouf'          1
'Glória Pires'          1
'Lady Gaga'             1
'Jon Voight'            1
Name: Lead_Actor, Length: 810, dtype: int64

In [35]:
oscars_df['Lead_Actor'].count()

1990

In [36]:
oscars_df['Supporting_Actor_1'].value_counts()

 'Meryl Streep'             13
 'Cate Blanchett'            9
 'Kate Winslet'              9
 'Ed Harris'                 9
 'Matt Damon'                9
                            ..
 'Shailene Woodley'          1
 'Janelle Monáe'             1
 'Jolene Rae Harrington'     1
 'Whoopi Goldberg'           1
 'Taylor Kitsch'             1
Name: Supporting_Actor_1, Length: 967, dtype: int64

In [37]:
oscars_df['Supporting_Actor_1'].count()

1990

In [38]:
oscars_df['Supporting_Actor_2'].value_counts()

 'Christopher Plummer'    9
 'Willem Dafoe'           9
 'Kevin Bacon'            7
 'Margot Robbie'          7
 'Ed Harris'              7
                         ..
 'Maria de Medeiros'      1
 'Werner De Smedt'        1
 'Michael Williams'       1
 'Heather Craney'         1
 'Mirjana Karanovic'      1
Name: Supporting_Actor_2, Length: 1067, dtype: int64

In [39]:
oscars_df['Supporting_Actor_2'].count()

1960

In [40]:
remove_quotation('Lead_Actor')
remove_quotation('Supporting_Actor_1')
remove_quotation('Supporting_Actor_2')

,IMDBId,movie title,casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2
0,tt0091763,Platoon,"'Charlie Sheen', 'Tom Berenger', 'Willem Dafoe'","'Drama', 'War'",English,USA,2h,R,6-Feb-87,92.0,6000000.0,Orion Pictures,Oliver Stone,NaN,Oliver Stone,Charlie Sheen,Tom Berenger,Willem Dafoe
1,tt0082979,Reds,"'Warren Beatty', 'Diane Keaton', 'Edward Herrm...","'Biography', 'Drama', 'History', 'Romance'",English,USA,3h 15min,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures,Warren Beatty,Trevor Griffiths,Warren Beatty,Warren Beatty,Diane Keaton,Edward Herrmann
2,tt0084434,An Officer and a Gentleman,"'Richard Gere', 'Debra Winger', 'David Keith'","'Drama', 'Romance'",English,USA,2h 4min,R,13-Aug-82,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,NaN,Taylor Hackford,Richard Gere,Debra Winger,David Keith
3,tt0119360,In & Out,"'Kevin Kline', 'Joan Cusack', 'Tom Selleck'","'Comedy', 'Romance'",English,USA,1h 30min,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures,Paul Rudnick,NaN,Frank Oz,Kevin Kline,Joan Cusack,Tom Selleck
4,tt0292542,Son of the Bride,"'Ricardo Darín', 'Héctor Alterio', 'Norma Alea...","'Comedy', 'Drama'",Spanish,Argentina,2h 3min,R,16-Aug-01,68.0,NaN,Sony Pictures Classics,Juan José Campanella,Fernando Castets,Juan José Campanella,Ricardo Darín,Héctor Alterio,Norma Aleandro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,NaN,Tuba Atlantic,"'Edvard Hægstad', 'Ingrid Viken', 'Terje Ranes'","'Short', 'Comedy', 'Drama'",Norwegian,Norway,25min,TV-MA,Jun-10,NaN,NaN,NaN,Linn-Jeanethe Kyed,NaN,Hallvar Witzø,Edvard Hægstad,Ingrid Viken,Terje Ranes
1986,NaN,The Lion King,"'Donald Glover', 'Beyoncé', 'Seth Rogen'","'Animation', 'Adventure', 'Drama', 'Family', '...",English,USA,1h 58min,PG,19-Jul-19,55.0,260000000.0,Walt Disney Studios Motion Pictures,Jeff Nathanson,Irene Mecchi,Jon Favreau,Donald Glover,Beyoncé,Seth Rogen
1987,NaN,Ford v Ferrari,"'Matt Damon', 'Christian Bale', 'Jon Bernthal'","'Action', 'Biography', 'Drama', 'Sport'",English,USA,2h 32min,PG-13,15-Nov-19,81.0,97600000.0,Twentieth Century Fox,Jez Butterworth,John-Henry Butterworth,James Mangold,Matt Damon,Christian Bale,Jon Bernthal
1988,NaN,Common Threads: Stories from the Quilt,"'Sara Lewinstein', 'David Mandell', 'Suzi Mand...","'Documentary', 'Biography', 'History'",English,USA,1h 19min,1h 19min,NaN,NaN,NaN,Direct Cinema Limited,Rob Epstein,Jeffrey Friedman,Rob Epstein,Sara Lewinstein,David Mandell,Suzi Mandell
1989,NaN,Wyatt Earp,"'Kevin Costner', 'Dennis Quaid', 'Gene Hackman'","'Adventure', 'Biography', 'Crime', 'Drama', 'W...",English,USA,3h 11min,PG-13,24-Jun-94,47.0,63000000.0,Warner Bros.,Dan Gordon,Lawrence Kasdan,Lawrence Kasdan,Kevin Costner,Dennis Quaid,Gene Hackman

In [41]:
oscars_df.drop(['casts'], axis=1,inplace=True)

### Explore genre

In [42]:
oscars_df['genre(s)'].unique()

array(["'Drama', 'War'", "'Biography', 'Drama', 'History', 'Romance'",
       "'Drama', 'Romance'", "'Comedy', 'Romance'", "'Comedy', 'Drama'",
       "'Drama', 'Music'", "'Drama'", "'Biography', 'Drama'",
       "'Drama', 'Western'", "'Drama', 'Thriller'",
       "'Drama', 'Mystery', 'Thriller'",
       "'Biography', 'Drama', 'Romance'",
       "'Biography', 'Drama', 'History'", "'Biography', 'Drama', 'Music'",
       "'Documentary', 'Drama'",
       "'Biography', 'Comedy', 'Drama', 'History'",
       "'Action', 'Crime', 'Drama', 'Mystery', 'Thriller'",
       "'Comedy', 'Drama', 'Romance'",
       "'Crime', 'Drama', 'Mystery', 'Thriller'",
       "'Biography', 'Drama', 'Sport'", "'Adventure', 'Drama', 'Mystery'",
       "'Documentary'", "'Crime', 'Drama'",
       "'Drama', 'Mystery', 'Sci-Fi', 'Thriller'",
       "'Biography', 'Drama', 'Music', 'War'",
       "'Crime', 'Drama', 'Romance', 'Thriller'",
       "'Drama', 'Mystery', 'Romance', 'Thriller'", "'Drama', 'History'",
       "'Drama', 'Music', 'Romance'",
       "'Biography', 'Drama', 'Thriller', 'War'",
       "'Comedy', 'Drama', 'Music', 'Romance'",
       "'Comedy', 'Drama', 'Mystery'",
       "'Action', 'Drama', 'History', 'Thriller'",
       "'Biography', 'Crime', 'Drama'", "'Adventure', 'Drama', 'Fantasy'",
       "'Comedy', 'Drama', 'Thriller'", "'Comedy', 'War'",
       "'Drama', 'Music', 'Musical'", "'Comedy', 'Drama', 'War'",
       "'Adventure', 'Drama', 'War'",
       "'Adventure', 'Biography', 'Crime', 'Drama', 'Thriller'",
       "'Comedy', 'Crime', 'Drama', 'Mystery', 'Romance'",
       "'Action', 'Comedy', 'Drama', 'Romance', 'Thriller'",
       "'Drama', 'History', 'War'",
       "'Action', 'Biography', 'Drama', 'History'",
       "'Crime', 'Drama', 'History', 'War'",
       "'Biography', 'Drama', 'History', 'Thriller', 'War'",
       "'Drama', 'Romance', 'War'",
       "'Drama', 'History', 'Thriller', 'War'", "'Romance', 'Drama'",
       "'Crime', 'Drama', 'War'", "'Drama', 'Mystery', 'War'",
       "'Drama', 'Thriller', 'War'", "'Mystery', 'Sci-Fi', 'Thriller'",
       "'Action', 'Biography', 'Drama', 'Sport'",
       "'Adventure', 'Biography', 'Drama'",
       "'Action', 'Adventure', 'Fantasy', 'Romance'",
       "'Adventure', 'Drama', 'Fantasy', 'Romance', 'Sci-Fi', 'Thriller'",
       "'Action', 'Drama', 'Sport'", "'Crime', 'Drama', 'Thriller'",
       "'Drama', 'Fantasy', 'Thriller'", "'Drama', 'Mystery', 'Romance'",
       "'Biography', 'Drama', 'War'",
       "'Action', 'Adventure', 'Drama', 'Fantasy'",
       "'Comedy', 'Crime', 'Drama', 'Thriller'",
       "'Biography', 'Drama', 'Mystery'", "'Drama', 'Mystery'",
       "'Crime', 'Drama', 'Thriller', 'War'",
       "'Comedy', 'Crime', 'Drama', 'Romance'", "'Romance', 'Sci-Fi'",
       "'Biography', 'Drama', 'History', 'War'",
       "'Biography', 'Drama', 'Thriller'",
       "'Drama', 'Musical', 'Romance'",
       "'Action', 'Crime', 'Drama', 'Thriller'",
       "'Comedy', 'Drama', 'Music', 'Musical', 'Romance'",
       "'Biography', 'Drama', 'Romance', 'Thriller', 'War'",
       "'Crime', 'Drama', 'Romance'", "'Comedy', 'Drama', 'Music'",
       "'Comedy', 'Crime'", "'Comedy', 'Drama', 'Fantasy'",
       "'Action', 'Adventure', 'Drama', 'History', 'War'",
       "'Adventure', 'Drama', 'Western'",
       "'Drama', 'History', 'Thriller'",
       "'Biography', 'Drama', 'History', 'Thriller'",
       "'Adventure', 'Drama', 'History'",
       "'Biography', 'Crime', 'Drama', 'History', 'Mystery', 'Thriller'",
       "'Drama', 'Fantasy', 'Mystery', 'Romance'", "'Comedy'",
       "'Action', 'Drama', 'War'",
       "'Comedy', 'Drama', 'History', 'Romance'",
       "'Comedy', 'Fantasy', 'Romance'", "'Action', 'Adventure'",
       "'Comedy', 'Drama', 'Sci-Fi'", "'Biography', 'Comedy', 'Drama'",
       "'Comedy', 'Romance', 'Drama'",
       "'Biography', 'Comedy', 'Drama', 'Music'",
       "'Drama', 'Horror', 'Musical', 'Thriller'",
       "'Drama', 'Family', 'Fantasy', 'Mystery'",
       "'Crime', 'Drama', 'Mystery', 'Thriller', 'Western'",
       "'Action', 'Adventure', 'Sci-Fi', 'Thriller'",
       "'Comedy', 'Crime', 'Drama'",
       "'Adventure', 'Drama', 'Musical', 'Sport'",
       "'Biography', 'Crime', 'Drama', 'History', 'Western'",
       "'Biography', 'Crime', 'Drama', 'Romance'",
       "'Comedy', 'Drama', 'Fantasy', 'Romance'",
       "'Crime', 'Drama', 'Mystery'",
       "'Crime', 'Drama', 'History', 'Mystery', 'Thriller'",
       "'Biography', 'Drama', 'Music', 'Romance'",
       "'Biography', 'Drama', 'Family'",
       "'Drama', 'History', 'Mystery', 'Thriller'", "'Drama', 'Sport'",
       "'Drama', 'Romance', 'Thriller', 'War'",
       "'Drama', 'Family', 'Sport'", "'Action', 'Adventure', 'Fantasy'",
       "'Documentary', 'Animation', 'Biography', 'Drama', 'History', 'Mystery', 'War'",
       "'Drama', 'Fantasy'", "'Biography', 'Comedy', 'Drama', 'Romance'",
       "'Adventure', 'Biography', 'Drama', 'History'",
       "'Adventure', 'Drama'", "'Adventure', 'Drama', 'Thriller', 'War'",
       "'Family', 'Sci-Fi'", "'Drama', 'Romance', 'Thriller'",
       "'Adventure', 'Comedy', 'Crime'",
       "'Action', 'Comedy', 'Crime', 'Music', 'Romance', 'Thriller'",
       "'Comedy', 'Drama', 'Family', 'History'",
       "'Comedy', 'Drama', 'Romance', 'War'", "'Drama', 'Musical'",
       "'Action', 'Biography', 'Drama', 'War'",
       "'Adventure', 'Drama', 'Romance'",
       "'Action', 'Biography', 'Drama', 'History', 'War'",
       "'Drama', 'Family', 'Romance'",
       "'Comedy', 'Drama', 'Romance', 'Sport'",
       "'Crime', 'Drama', 'Fantasy', 'Mystery'",
       "'Drama', 'History', 'Romance', 'War'",
       "'Drama', 'History', 'Music', 'Romance'",
       "'Biography', 'Drama', 'History', 'Romance', 'Sport'",
       "'Drama', 'Sci-Fi', 'Thriller'", "'Action', 'Adventure', 'Drama'",
       "'Drama', 'Romance', 'Sci-Fi'",
       "'Biography', 'Comedy', 'Crime', 'Drama'",
       "'Drama', 'History', 'Music', 'Romance', 'War'",
       "'Action', 'Biography', 'Crime', 'Drama', 'History', 'Thriller'",
       "'Biography', 'Comedy', 'Drama', 'War'",
       "'Biography', 'Drama', 'History', 'Sport'",
       "'Crime', 'Drama', 'Romance', 'Thriller', 'War'",
       "'Drama', 'Mystery', 'Romance', 'War'",
       "'Adventure', 'Drama', 'Sci-Fi'",
       "'Action', 'Drama', 'Family', 'Sport'",
       "'Action', 'Adventure', 'Drama', 'History', 'Western'",
       "'Adventure', 'Drama', 'Thriller'",
       "'Comedy', 'Drama', 'History', 'War'",
       "'Comedy', 'Crime', 'Thriller'", "'Action', 'Comedy', 'War'",
       "'Drama', 'History', 'Musical', 'Romance', 'War'",
       "'Action', 'Adventure', 'Fantasy', 'Sci-Fi'",
       "'Crime', 'Drama', 'Music', 'Romance'",
       "'Drama', 'Fantasy', 'Romance'", "'Comedy', 'Drama', 'Family'",
       "'Adventure', 'Comedy', 'Drama'", "'Comedy', 'Western'",
       "'Drama', 'History', 'Romance'",
       "'Biography', 'Crime', 'Drama', 'History'",
       "'Drama', 'Fantasy', 'War'", "'Comedy', 'Music', 'Romance'",
       "'Action', 'Adventure', 'Drama', 'Thriller'",
       "'Adventure', 'Comedy', 'Drama', 'Music'",
       "'Crime', 'Drama', 'Music'", "'Drama', 'Comedy'",
       "'Crime', 'Mystery', 'Thriller'",
       "'Biography', 'Drama', 'Music', 'Musical'",
       "'Biography', 'Crime', 'Drama', 'Mystery', 'Thriller'",
       "'History', 'Musical'", "'Biography', 'Comedy', 'Drama', 'Sport'",
       "'Drama', 'Family'", "'Action', 'Adventure', 'History'",
       "'Adventure', 'Drama', 'History', 'Romance', 'War'",
       "'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Musical'",
       "'Biography', 'Drama', 'History', 'Music'",
       "'Biography', 'Drama', 'History', 'Mystery', 'Thriller'",
       "'Adventure', 'Family', 'Sport'",
       "'Comedy', 'Drama', 'Music', 'War'", "'Comedy', 'Musical'",
       "'Biography', 'Crime', 'Drama', 'History', 'Thriller', 'War'",
       "'Action', 'Biography', 'Drama', 'History', 'Romance', 'War'",
       "'Crime', 'Mystery', 'Romance', 'Thriller'",
       "'Biography', 'Crime', 'Drama', 'Thriller'",
       "'Adventure', 'Drama', 'History', 'Romance'",
       "'Action', 'Comedy', 'Crime', 'Drama'",
       "'Adventure', 'Crime', 'Drama'", "'Comedy', 'Crime', 'Musical'",
       "'Action', 'Crime', 'Drama', 'Thriller', 'Western'",
       "'Horror', 'Mystery', 'Thriller'", "'Crime', 'Thriller'",
       "'Comedy', 'Crime', 'Romance'", "'Drama', 'Sport', 'Thriller'",
       "'Crime', 'Drama', 'Mystery', 'War'",
       "'Action', 'Drama', 'History', 'Thriller', 'War'",
       "'Drama', 'Fantasy', 'Romance', 'Thriller'", "'Drama', 'Horror'",
       "'Animation', 'Adventure', 'Drama', 'Family', 'Fantasy'",
       "'Short', 'Comedy', 'Drama', 'Family'", "'Mystery', 'Thriller'",
       "'Crime', 'Drama', 'Musical'",
       "'Short', 'Biography', 'Drama', 'Family', 'Romance'",
       "'Crime', 'Drama', 'Fantasy', 'Romance', 'Thriller'",
       "'Short', 'Comedy'", "'Animation', 'Comedy', 'Family', 'Sport'",
       "'Short', 'Drama'",
       "'Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Musical', 'Romance'",
       "'Adventure', 'Family'", "'Short', 'Crime', 'Drama'", "'Short'",
       "'Adventure', 'Drama', 'Sci-Fi', 'Thriller'",
       "'Action', 'Adventure', 'Drama', 'Sci-Fi'",
       "'Action', 'Adventure', 'Drama', 'Romance', 'War'",
       "'Action', 'Sci-Fi'",
       "'Animation', 'Action', 'Adventure', 'Family', 'Sci-Fi'",
       "'Drama', 'Sci-Fi'", "'Documentary', 'Biography', 'Music'",
       "'Action', 'Adventure', 'Drama', 'Sci-Fi', 'Thriller'",
       "'Documentary', 'Short', 'Drama'",
       "'Drama', 'Mystery', 'Romance', 'Thriller', 'War'",
       "'Short', 'Comedy', 'Drama'", "'Drama', 'History', 'Western'",
       "'Animation', 'Short', 'Biography'",
       "'Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'",
       "'Drama', 'Romance', 'Music'", "'Drama', 'History', 'Horror'",
       "'Comedy', 'Short'",
       "'Biography', 'Crime', 'Drama', 'History', 'Mystery', 'Romance'",
       "'Documentary', 'Short', 'Biography'",
       "'Animation', 'Adventure', 'Family', 'Sci-Fi'",
       "'Documentary', 'Short'", "'Documentary', 'News'",
       "'Action', 'Adventure', 'Comedy', 'Thriller', 'Western'",
       "'Action', 'Adventure', 'Comedy', 'Romance', 'Thriller', 'Western'",
       "'Action', 'Adventure', 'Comedy', 'Sci-Fi'",
       "'Animation', 'Comedy', 'Drama', 'Family'",
       "'Documentary', 'Music'", "'Drama', 'Short'",
       "'Animation', 'Adventure', 'Comedy', 'Crime', 'Family'",
       "'Adventure', 'Family', 'Fantasy', 'Mystery'",
       "'Adventure', 'Comedy', 'Family', 'Fantasy'", "'Musical', 'Short'",
       "'Action', 'Drama', 'Sci-Fi', 'Thriller'",
       "'Animation', 'Action', 'Adventure', 'Family', 'Mystery'",
       "'Action', 'Adventure', 'Sci-Fi'",
       "'Animation', 'Short', 'Comedy', 'Fantasy'",
       "'Adventure', 'Family', 'Fantasy'",
       "'Adventure', 'Mystery', 'Sci-Fi', 'Thriller'",
       "'Animation', 'Comedy', 'Fantasy', 'Musical'",
       "'Drama', 'Fantasy', 'History', 'Music', 'Musical', 'Romance'",
       "'Adventure', 'Comedy', 'Romance'",
       "'Action', 'Comedy', 'Thriller'", "'Action', 'Comedy', 'Fantasy'",
       "'Animation', 'Comedy', 'Family', 'Fantasy', 'Musical', 'Romance'",
       "'Comedy', 'Horror'", "'Short', 'Drama', 'Family', 'Thriller'",
       "'Action', 'Family', 'Romance', 'Sport'", "'Documentary', 'War'",
       "'Documentary', 'Short', 'Biography', 'Drama', 'Music'",
       "'Horror', 'Thriller'", "'Animation', 'Short'",
       "'Action', 'Adventure', 'Comedy', 'Romance'",
       "'Action', 'Biography', 'Drama', 'Romance', 'War'",
       "'Animation', 'Adventure', 'Drama', 'Family', 'Fantasy', 'Musical', 'Mystery', 'Romance'",
       "'Drama', 'Romance', 'Short'",
       "'Animation', 'Biography', 'Crime', 'Drama', 'Family', 'Mystery'",
       "'Short', 'Drama', 'Music', 'Romance'",
       "'Action', 'Adventure', 'Thriller'",
       "'Animation', 'Short', 'Drama', 'Western'",
       "'Animation', 'Short', 'Comedy', 'Family', 'Fantasy'",
       "'Action', 'War'",
       "'Adventure', 'Comedy', 'Drama', 'Family', 'Fantasy'",
       "'Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Musical'",
       "'Comedy', 'Fantasy'",
       "'Animation', 'Adventure', 'Comedy', 'Family'",
       "'Animation', 'Short', 'Action', 'Comedy', 'Crime'",
       "'Animation', 'Drama', 'Family', 'War'",
       "'Action', 'Comedy', 'Crime', 'Thriller'",
       "'Animation', 'Action', 'Adventure', 'Comedy', 'Family', 'Sci-Fi'",
       "'Documentary', 'Biography', 'Sport'",
       "'Action', 'Crime', 'Sci-Fi', 'Thriller', 'Western'",
       "'Animation', 'Short', 'Action', 'Comedy', 'Fantasy'",
       "'Animation', 'Short', 'Comedy', 'Crime', 'Family', 'Sci-Fi'",
       "'Animation', 'Drama', 'Family', 'Mystery'",
       "'Comedy', 'Romance', 'Sci-Fi'",
       "'Adventure', 'Mystery', 'Sci-Fi'",
       "'Animation', 'Adventure', 'Family', 'Fantasy', 'Music', 'Mystery'",
       "'Documentary', 'Short', 'Drama', 'Family'",
       "'Documentary', 'Biography', 'War'",
       "'Drama', 'Romance', 'War', 'Western'", "'Documentary', 'Sport'",
       "'Documentary', 'Biography', 'Comedy'",
       "'Short', 'Drama', 'History'",
       "'Action', 'Drama', 'Romance', 'Thriller', 'War'",
       "'Action', 'Drama', 'History', 'War'",
       "'Animation', 'Short', 'Drama', 'Family'",
       "'Animation', 'Family', 'Fantasy', 'Musical'",
       "'Animation', 'Adventure', 'Family', 'Fantasy'",
       "'Action', 'Thriller'",
       "'Animation', 'Drama', 'Family', 'Musical', 'Romance'",
       "'Adventure', 'Fantasy'", "'Short', 'Romance', 'Comedy'",
       "'Animation', 'Adventure', 'Drama', 'Family', 'Western'",
       "'Short', 'Comedy', 'Drama', 'Sport'",
       "'Drama', 'Horror', 'Sci-Fi'", "'Animation', 'Short', 'Drama'",
       "'Comedy', 'Crime', 'Drama', 'Mystery', 'Thriller'",
       "'Drama', 'Romance', 'Sport'", "'Action', 'Sci-Fi', 'Thriller'",
       "'Action', 'Crime', 'Thriller'",
       "'Short', 'Comedy', 'Adventure', 'Romance'",
       "'Biography', 'Drama', 'Fantasy', 'Romance'",
       "'Family', 'Comedy', 'Animation', 'Short'",
       "'Animation', 'Biography', 'Drama', 'Family', 'History', 'War'",
       "'Documentary', 'History', 'War'",
       "'Animation', 'Family', 'Fantasy'",
       "'Animation', 'Short', 'Comedy'", "'Short', 'Comedy', 'Romance'",
       "'Action', 'Adventure', 'Family', 'Fantasy', 'Thriller'",
       "'Action', 'Mystery', 'Thriller'",
       "'Adventure', 'Family', 'Fantasy', 'Romance'",
       "'Drama', 'Horror', 'Romance', 'Sci-Fi'", "'Horror'",
       "'Action', 'Adventure', 'Comedy', 'Fantasy', 'Sci-Fi', 'Thriller'",
       "'Short', 'Comedy', 'Drama', 'Fantasy'", "'Short', 'Drama', 'War'",
       "'Comedy', 'Drama', 'Music', 'Mystery'",
       "'Animation', 'Short', 'Adventure', 'Mystery', 'Sci-Fi'",
       "'Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Sci-Fi'",
       "'Action', 'Drama', 'History', 'Romance'",
       "'Adventure', 'Comedy', 'Fantasy', 'Mystery'",
       "'Animation', 'Drama', 'Family', 'Fantasy', 'Thriller'",
       "'Comedy', 'Drama', 'Romance', 'Western'",
       "'Animation', 'Comedy', 'Family', 'Fantasy', 'Mystery'",
       "'Adventure', 'Drama', 'Fantasy', 'Romance'",
       "'Drama', 'Family', 'Fantasy'", "'Short', 'Drama', 'Music'",
       "'Animation', 'Action', 'Adventure', 'Family', 'Fantasy'",
       "'Short', 'Adventure', 'Drama'", "'Documentary', 'Biography'",
       "'Short', 'Drama', 'Thriller', 'War'",
       "'Animation', 'Adventure', 'Comedy', 'Crime', 'Drama', 'Family'",
       "'Horror', 'Sci-Fi', 'Thriller'", "'Documentary', 'Crime'",
       "'Short', 'Drama', 'Family', 'War'",
       "'Action', 'Crime', 'Drama', 'Romance', 'Western'",
       "'Animation', 'Adventure', 'Family', 'Fantasy', 'Mystery'",
       "'Documentary', 'Biography', 'Crime', 'History'",
       "'Animation', 'Adventure', 'Drama', 'Family', 'Musical'",
       "'Documentary', 'Biography', 'History'",
       "'Animation', 'Short', 'Action', 'Family', 'Fantasy', 'Thriller'",
       "'Adventure', 'Family', 'Drama'",
       "'Documentary', 'Biography', 'News'", "'Short', 'Family'",
       "'Adventure', 'Comedy', 'Sci-Fi'",
       "'Animation', 'Adventure', 'Family', 'Romance'",
       "'Animation', 'Comedy', 'Drama'",
       "'Animation', 'Adventure', 'Comedy', 'Drama', 'Family', 'Fantasy', 'Sci-Fi'",
       "'Drama', 'Family', 'Fantasy', 'Romance'",
       "'Short', 'Drama', 'Thriller'",
       "'Animation', 'Crime', 'Drama', 'Music', 'Romance'",
       "'Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Mystery'",
       "'Short', 'Drama', 'History', 'War'",
       "'Action', 'Adventure', 'Western'",
       "'Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Horror', 'Mystery', 'Sci-Fi'",
       "'Animation', 'Short', 'Drama', 'Romance'",
       "'Drama', 'Fantasy', 'History', 'Mystery', 'Romance', 'Thriller'",
       "'Animation', 'Family', 'Fantasy', 'Musical', 'Romance'",
       "'Documentary', 'Drama', 'Sport'", "'Documentary', 'History'",
       "'Action', 'Adventure', 'Drama', 'Romance'",
       "'Adventure', 'Comedy', 'Fantasy'", "'Short', 'Drama', 'Romance'",
       "'Short', 'Sport'", "'Action', 'Adventure', 'Comedy'",
       "'Short', 'Sci-Fi'", "'Drama', 'Fantasy', 'Horror', 'Mystery'",
       "'Adventure', 'Comedy', 'Family'",
       "'Action', 'Crime', 'Sci-Fi', 'Thriller'",
       "'Action', 'Adventure', 'Comedy', 'Crime'",
       "'Action', 'Adventure', 'Comedy', 'Crime', 'Romance', 'Thriller'",
       "'Adventure', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'",
       "'Adventure', 'Fantasy', 'Mystery', 'Thriller'",
       "'Animation', 'Action', 'Adventure', 'Comedy', 'Family', 'Fantasy'",
       "'Adventure', 'Comedy', 'Crime', 'Music'",
       "'Drama', 'Short', 'Comedy'",
       "'Documentary', 'Animation', 'Short', 'Biography'",
       "'Short', 'Fantasy'",
       "'Adventure', 'Biography', 'Crime', 'Drama', 'Western'"],
      dtype=object)

In [43]:
oscars_df[['genre']] = oscars_df['genre(s)'].apply(lambda x: pd.Series(''.join(x.split(',')[0:2])))

In [44]:
oscars_df.head()

,IMDBId,movie title,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre
0,tt0091763,Platoon,"'Drama', 'War'",English,USA,2h,R,6-Feb-87,92.0,6000000.0,Orion Pictures,Oliver Stone,NaN,Oliver Stone,Charlie Sheen,Tom Berenger,Willem Dafoe,'Drama' 'War'
1,tt0082979,Reds,"'Biography', 'Drama', 'History', 'Romance'",English,USA,3h 15min,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures,Warren Beatty,Trevor Griffiths,Warren Beatty,Warren Beatty,Diane Keaton,Edward Herrmann,'Biography' 'Drama'
2,tt0084434,An Officer and a Gentleman,"'Drama', 'Romance'",English,USA,2h 4min,R,13-Aug-82,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,NaN,Taylor Hackford,Richard Gere,Debra Winger,David Keith,'Drama' 'Romance'
3,tt0119360,In & Out,"'Comedy', 'Romance'",English,USA,1h 30min,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures,Paul Rudnick,NaN,Frank Oz,Kevin Kline,Joan Cusack,Tom Selleck,'Comedy' 'Romance'
4,tt0292542,Son of the Bride,"'Comedy', 'Drama'",Spanish,Argentina,2h 3min,R,16-Aug-01,68.0,NaN,Sony Pictures Classics,Juan José Campanella,Fernando Castets,Juan José Campanella,Ricardo Darín,Héctor Alterio,Norma Aleandro,'Comedy' 'Drama'

In [45]:
oscars_df['genre'].value_counts()

'Comedy' 'Drama'       231
'Biography' 'Drama'    212
'Drama'                176
'Drama' 'Romance'      141
'Crime' 'Drama'        137
                      ...
'Animation' 'Crime'      1
'Short' 'Sci-Fi'         1
'Short' 'Sport'          1
'Romance' 'Sci-Fi'       1
'Short' 'Fantasy'        1
Name: genre, Length: 92, dtype: int64

In [46]:
oscars_df['genre'].count()

1990

In [47]:
#oscars_df['subgenre1'].count()

In [48]:
oscars_df.drop(['genre(s)'], axis=1,inplace=True)

In [49]:
oscars_df.head()

,IMDBId,movie title,language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre
0,tt0091763,Platoon,English,USA,2h,R,6-Feb-87,92.0,6000000.0,Orion Pictures,Oliver Stone,NaN,Oliver Stone,Charlie Sheen,Tom Berenger,Willem Dafoe,'Drama' 'War'
1,tt0082979,Reds,English,USA,3h 15min,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures,Warren Beatty,Trevor Griffiths,Warren Beatty,Warren Beatty,Diane Keaton,Edward Herrmann,'Biography' 'Drama'
2,tt0084434,An Officer and a Gentleman,English,USA,2h 4min,R,13-Aug-82,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,NaN,Taylor Hackford,Richard Gere,Debra Winger,David Keith,'Drama' 'Romance'
3,tt0119360,In & Out,English,USA,1h 30min,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures,Paul Rudnick,NaN,Frank Oz,Kevin Kline,Joan Cusack,Tom Selleck,'Comedy' 'Romance'
4,tt0292542,Son of the Bride,Spanish,Argentina,2h 3min,R,16-Aug-01,68.0,NaN,Sony Pictures Classics,Juan José Campanella,Fernando Castets,Juan José Campanella,Ricardo Darín,Héctor Alterio,Norma Aleandro,'Comedy' 'Drama'

In [50]:
remove_quotation('genre')

,IMDBId,movie title,language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre
0,tt0091763,Platoon,English,USA,2h,R,6-Feb-87,92.0,6000000.0,Orion Pictures,Oliver Stone,NaN,Oliver Stone,Charlie Sheen,Tom Berenger,Willem Dafoe,Drama' 'War
1,tt0082979,Reds,English,USA,3h 15min,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures,Warren Beatty,Trevor Griffiths,Warren Beatty,Warren Beatty,Diane Keaton,Edward Herrmann,Biography' 'Drama
2,tt0084434,An Officer and a Gentleman,English,USA,2h 4min,R,13-Aug-82,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,NaN,Taylor Hackford,Richard Gere,Debra Winger,David Keith,Drama' 'Romance
3,tt0119360,In & Out,English,USA,1h 30min,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures,Paul Rudnick,NaN,Frank Oz,Kevin Kline,Joan Cusack,Tom Selleck,Comedy' 'Romance
4,tt0292542,Son of the Bride,Spanish,Argentina,2h 3min,R,16-Aug-01,68.0,NaN,Sony Pictures Classics,Juan José Campanella,Fernando Castets,Juan José Campanella,Ricardo Darín,Héctor Alterio,Norma Aleandro,Comedy' 'Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,NaN,Tuba Atlantic,Norwegian,Norway,25min,TV-MA,Jun-10,NaN,NaN,NaN,Linn-Jeanethe Kyed,NaN,Hallvar Witzø,Edvard Hægstad,Ingrid Viken,Terje Ranes,Short' 'Comedy
1986,NaN,The Lion King,English,USA,1h 58min,PG,19-Jul-19,55.0,260000000.0,Walt Disney Studios Motion Pictures,Jeff Nathanson,Irene Mecchi,Jon Favreau,Donald Glover,Beyoncé,Seth Rogen,Animation' 'Adventure
1987,NaN,Ford v Ferrari,English,USA,2h 32min,PG-13,15-Nov-19,81.0,97600000.0,Twentieth Century Fox,Jez Butterworth,John-Henry Butterworth,James Mangold,Matt Damon,Christian Bale,Jon Bernthal,Action' 'Biography
1988,NaN,Common Threads: Stories from the Quilt,English,USA,1h 19min,1h 19min,NaN,NaN,NaN,Direct Cinema Limited,Rob Epstein,Jeffrey Friedman,Rob Epstein,Sara Lewinstein,David Mandell,Suzi Mandell,Documentary' 'Biography
1989,NaN,Wyatt Earp,English,USA,3h 11min,PG-13,24-Jun-94,47.0,63000000.0,Warner Bros.,Dan Gordon,Lawrence Kasdan,Lawrence Kasdan,Kevin Costner,Dennis Quaid,Gene Hackman,Adventure' 'Biography

## Explore Runtime

In [51]:
oscars_df['runtime (mins)'].value_counts()

1h 45min    58
1h 58min    47
2h          45
2h 1min     42
2h 4min     40
            ..
2h 48min     1
3h 14min     1
5h 57min     1
52min        1
3h 29min     1
Name: runtime (mins), Length: 156, dtype: int64

In [52]:
import datetime
def runtime_to_minutes(runtimestring):
    if 'h' in runtimestring:
        runtime = runtimestring.split('h')
        minutes = int(runtime[0])*60 
        if 'min' in runtime[1]:
            mins = runtime[1].split('min')
            minutes += int(mins[0])
    else:
        runtime_minutes = runtimestring.split('min')
        minutes = int(runtime_minutes[0])
        
    return minutes

In [53]:
oscars_df['runtime (mins)'] = oscars_df['runtime (mins)'].apply(runtime_to_minutes)

In [54]:
oscars_df['runtime (mins)'].value_counts()

105    58
118    47
120    45
121    42
124    40
       ..
166     1
57      1
56      1
52      1
357     1
Name: runtime (mins), Length: 156, dtype: int64

In [55]:
bool1 = oscars_df['runtime (mins)'] < 70
oscars_df[bool1]
oscars_df = oscars_df.drop(oscars_df[bool1].index)

It looks like all the movies are feature length so we do not need to delete any columns.Now I want to explore Release Date.

Change release date to datetime

In [56]:
oscars_df.head()

,IMDBId,movie title,language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre
0,tt0091763,Platoon,English,USA,120,R,6-Feb-87,92.0,6000000.0,Orion Pictures,Oliver Stone,NaN,Oliver Stone,Charlie Sheen,Tom Berenger,Willem Dafoe,Drama' 'War
1,tt0082979,Reds,English,USA,195,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures,Warren Beatty,Trevor Griffiths,Warren Beatty,Warren Beatty,Diane Keaton,Edward Herrmann,Biography' 'Drama
2,tt0084434,An Officer and a Gentleman,English,USA,124,R,13-Aug-82,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,NaN,Taylor Hackford,Richard Gere,Debra Winger,David Keith,Drama' 'Romance
3,tt0119360,In & Out,English,USA,90,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures,Paul Rudnick,NaN,Frank Oz,Kevin Kline,Joan Cusack,Tom Selleck,Comedy' 'Romance
4,tt0292542,Son of the Bride,Spanish,Argentina,123,R,16-Aug-01,68.0,NaN,Sony Pictures Classics,Juan José Campanella,Fernando Castets,Juan José Campanella,Ricardo Darín,Héctor Alterio,Norma Aleandro,Comedy' 'Drama

In [57]:
oscars_df.drop(oscars_df.loc[oscars_df['release date']=='Episode aired 29 January 1996'].index, inplace=True)

In [58]:
oscars_df['release_date'] = pd.to_datetime(oscars_df['release date'])

In [59]:
oscars_df.head()

,IMDBId,movie title,language,country,runtime (mins),mpaarating,release date,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre,release_date
0,tt0091763,Platoon,English,USA,120,R,6-Feb-87,92.0,6000000.0,Orion Pictures,Oliver Stone,NaN,Oliver Stone,Charlie Sheen,Tom Berenger,Willem Dafoe,Drama' 'War,1987-02-06
1,tt0082979,Reds,English,USA,195,PG,25-Dec-81,76.0,32000000.0,Paramount Pictures,Warren Beatty,Trevor Griffiths,Warren Beatty,Warren Beatty,Diane Keaton,Edward Herrmann,Biography' 'Drama,1981-12-25
2,tt0084434,An Officer and a Gentleman,English,USA,124,R,13-Aug-82,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,NaN,Taylor Hackford,Richard Gere,Debra Winger,David Keith,Drama' 'Romance,1982-08-13
3,tt0119360,In & Out,English,USA,90,PG-13,19-Sep-97,70.0,35000000.0,Paramount Pictures,Paul Rudnick,NaN,Frank Oz,Kevin Kline,Joan Cusack,Tom Selleck,Comedy' 'Romance,1997-09-19
4,tt0292542,Son of the Bride,Spanish,Argentina,123,R,16-Aug-01,68.0,NaN,Sony Pictures Classics,Juan José Campanella,Fernando Castets,Juan José Campanella,Ricardo Darín,Héctor Alterio,Norma Aleandro,Comedy' 'Drama,2001-08-16

In [60]:
oscars_df.drop(['release date'], axis=1,inplace=True)

## Explore Metacritic and see how many NaN we retrieve

In [61]:
oscars_df.groupby('metacritic score').tail()

,IMDBId,movie title,language,country,runtime (mins),mpaarating,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre,release_date
53,tt1065073,Boyhood,English,USA,165,R,100.0,4000000.0,IFC Films,Richard Linklater,NaN,Richard Linklater,Ellar Coltrane,Patricia Arquette,Ethan Hawke,Drama,2014-08-15
132,tt0111495,Three Colors: Red,French,Switzerland,99,R,100.0,NaN,Miramax,Krzysztof Kieslowski,Krzysztof Piesiewicz,Krzysztof Kieslowski,Irène Jacob,Jean-Louis Trintignant,Frédérique Feder,Drama' 'Mystery,1994-11-23
161,tt0083922,Fanny and Alexander,Swedish,Sweden,188,R,100.0,6000000.0,Embassy Pictures,Ingmar Bergman,NaN,Ingmar Bergman,Bertil Guve,Pernilla Allwin,Kristina Adolphson,Drama,1982-12-17
164,tt0097937,My Left Foot,English,Ireland,103,R,97.0,NaN,Miramax,Shane Connaughton,Jim Sheridan,Jim Sheridan,Daniel Day-Lewis,Brenda Fricker,Alison Whelan,Biography' 'Drama,1990-03-30
257,tt0103939,Chaplin,English,UK,143,PG-13,47.0,31000000.0,TriStar Pictures,David Robinson,Charles Chaplin,Richard Attenborough,Robert Downey Jr.,Geraldine Chaplin,Paul Rhys,Biography' 'Comedy,1993-01-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1984,NaN,Monster,English,USA,109,R,74.0,8000000.0,Newmarket Films,Patty Jenkins,NaN,Patty Jenkins,Charlize Theron,Christina Ricci,Bruce Dern,Biography' 'Crime,2004-01-30
1986,NaN,The Lion King,English,USA,118,PG,55.0,260000000.0,Walt Disney Studios Motion Pictures,Jeff Nathanson,Irene Mecchi,Jon Favreau,Donald Glover,Beyoncé,Seth Rogen,Animation' 'Adventure,2019-07-19
1987,NaN,Ford v Ferrari,English,USA,152,PG-13,81.0,97600000.0,Twentieth Century Fox,Jez Butterworth,John-Henry Butterworth,James Mangold,Matt Damon,Christian Bale,Jon Bernthal,Action' 'Biography,2019-11-15
1988,NaN,Common Threads: Stories from the Quilt,English,USA,79,1h 19min,NaN,NaN,Direct Cinema Limited,Rob Epstein,Jeffrey Friedman,Rob Epstein,Sara Lewinstein,David Mandell,Suzi Mandell,Documentary' 'Biography,NaT
1989,NaN,Wyatt Earp,English,USA,191,PG-13,47.0,63000000.0,Warner Bros.,Dan Gordon,Lawrence Kasdan,Lawrence Kasdan,Kevin Costner,Dennis Quaid,Gene Hackman,Adventure' 'Biography,1994-06-24

In [62]:
bool1 = pd.isnull(oscars_df['metacritic score'])
oscars_df[bool1]

,IMDBId,movie title,language,country,runtime (mins),mpaarating,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre,release_date
7,tt0082736,Mephisto,Hungarian,West Germany,144,Unrated,NaN,NaN,Analysis Film Releasing Corporation,Péter Dobai,István Szabó,István Szabó,Klaus Maria Brandauer,Krystyna Janda,Ildikó Bánsági,Drama,1982-03-22
9,tt0087027,Camila,Spanish,Argentina,105,R,NaN,NaN,European Classics,María Luisa Bemberg,Beda Docampo Feijóo,María Luisa Bemberg,Susú Pecoraro,Imanol Arias,Héctor Alterio,Drama' 'Romance,1985-03-15
10,tt0094924,A Cry in the Dark,English,Australia,120,PG-13,NaN,15000000.0,Warner Bros.,John Bryson,Robert Caswell,Fred Schepisi,Meryl Streep,Sam Neill,Dale Reeves,Biography' 'Drama,1988-11-11
15,tt0095530,Little Dorrit,English,UK,357,G,NaN,NaN,Cannon Film Distributors,Charles Dickens,Christine Edzard,Christine Edzard,Derek Jacobi,Alec Guinness,Joan Greenwood,Drama' 'Romance,1988-10-21
29,tt0111797,Eat Drink Man Woman,Mandarin,Taiwan,124,Not Rated,NaN,NaN,The Samuel Goldwyn Company,Ang Lee,James Schamus,Ang Lee,Sihung Lung,Kuei-Mei Yang,Yu-Wen Wang,Comedy' 'Drama,1994-08-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1940,NaN,Anne Frank Remembered,English,UK,117,PG,NaN,NaN,Sony Pictures Classics,Jon Blair,Anne Frank,Jon Blair,Kenneth Branagh,Glenn Close,Janny Brandes-Brilslijper,Documentary' 'Biography,1995-06-08
1949,NaN,For the Boys,English,USA,138,R,NaN,40000000.0,Twentieth Century Fox,Neal Jimenez,Lindy Laub,Mark Rydell,Bette Midler,James Caan,George Segal,Comedy' 'Drama,1991-11-27
1968,NaN,Börn náttúrunnar,Icelandic,Iceland,82,1h 22min,NaN,NaN,Northern Arts Entertainment,Friðrik Þór Friðriksson,Einar Guðmundsson,Friðrik Þór Friðriksson,Gísli Halldórsson,Sigríður Hagalín,Baldvin Halldórsson,Drama' 'Romance,NaT
1983,NaN,Confidence,Hungarian,Hungary,105,Not Rated,NaN,NaN,New Yorker Films,István Szabó,István Szabó,István Szabó,Ildikó Bánsági,Péter Andorai,Oszkárné Gombik,Drama,1980-01-10
1988,NaN,Common Threads: Stories from the Quilt,English,USA,79,1h 19min,NaN,NaN,Direct Cinema Limited,Rob Epstein,Jeffrey Friedman,Rob Epstein,Sara Lewinstein,David Mandell,Suzi Mandell,Documentary' 'Biography,NaT

Since we are looking for the metacritc score if a movie doesn't have a score it wont provide much information and will be dropped

In [63]:
oscars_df.dropna(subset=['metacritic score'],inplace=True)

In [64]:
oscars_df.shape

(1532, 17)

Now I want to explore some columns that may give some good information for the realtionship between oscars nominated directors and actors

In [65]:
directors_df = oscars_df.groupby(['director','Lead_Actor'])['Lead_Actor'].transform('count')

In [66]:
oscars_df['Total_Movies_Lead_Actor_Director'] =  oscars_df.groupby(['director','Lead_Actor'])['Lead_Actor'].transform('count')

In [67]:
oscars_df

,IMDBId,movie title,language,country,runtime (mins),mpaarating,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre,release_date,Total_Movies_Lead_Actor_Director
0,tt0091763,Platoon,English,USA,120,R,92.0,6000000.0,Orion Pictures,Oliver Stone,NaN,Oliver Stone,Charlie Sheen,Tom Berenger,Willem Dafoe,Drama' 'War,1987-02-06,4
1,tt0082979,Reds,English,USA,195,PG,76.0,32000000.0,Paramount Pictures,Warren Beatty,Trevor Griffiths,Warren Beatty,Warren Beatty,Diane Keaton,Edward Herrmann,Biography' 'Drama,1981-12-25,5
2,tt0084434,An Officer and a Gentleman,English,USA,124,R,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,NaN,Taylor Hackford,Richard Gere,Debra Winger,David Keith,Drama' 'Romance,1982-08-13,2
3,tt0119360,In & Out,English,USA,90,PG-13,70.0,35000000.0,Paramount Pictures,Paul Rudnick,NaN,Frank Oz,Kevin Kline,Joan Cusack,Tom Selleck,Comedy' 'Romance,1997-09-19,2
4,tt0292542,Son of the Bride,Spanish,Argentina,123,R,68.0,NaN,Sony Pictures Classics,Juan José Campanella,Fernando Castets,Juan José Campanella,Ricardo Darín,Héctor Alterio,Norma Aleandro,Comedy' 'Drama,2001-08-16,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,NaN,The Time Machine,English,USA,96,PG-13,42.0,80000000.0,DreamWorks Distribution,H.G. Wells,David Duncan,Simon Wells,Guy Pearce,Yancey Arias,Mark Addy,Action' 'Adventure,2002-03-08,1
1984,NaN,Monster,English,USA,109,R,74.0,8000000.0,Newmarket Films,Patty Jenkins,NaN,Patty Jenkins,Charlize Theron,Christina Ricci,Bruce Dern,Biography' 'Crime,2004-01-30,2
1986,NaN,The Lion King,English,USA,118,PG,55.0,260000000.0,Walt Disney Studios Motion Pictures,Jeff Nathanson,Irene Mecchi,Jon Favreau,Donald Glover,Beyoncé,Seth Rogen,Animation' 'Adventure,2019-07-19,1
1987,NaN,Ford v Ferrari,English,USA,152,PG-13,81.0,97600000.0,Twentieth Century Fox,Jez Butterworth,John-Henry Butterworth,James Mangold,Matt Damon,Christian Bale,Jon Bernthal,Action' 'Biography,2019-11-15,2
1989,NaN,Wyatt Earp,English,USA,191,PG-13,47.0,63000000.0,Warner Bros.,Dan Gordon,Lawrence Kasdan,Lawrence Kasdan,Kevin Costner,Dennis Quaid,Gene Hackman,Adventure' 'Biography,1994-06-24,1

In [68]:
oscars_df.sort_values('Total_Movies_Lead_Actor_Director',ascending=False)

,IMDBId,movie title,language,country,runtime (mins),mpaarating,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre,release_date,Total_Movies_Lead_Actor_Director
1761,NaN,The Aviator,English,Germany,170,PG-13,77.0,110000000.0,Miramax,John Logan,NaN,Martin Scorsese,Leonardo DiCaprio,Cate Blanchett,Kate Beckinsale,Biography' 'Drama,2004-12-25,7
268,tt0407887,The Departed,English,USA,151,R,85.0,90000000.0,Warner Bros.,William Monahan,Alan Mak,Martin Scorsese,Leonardo DiCaprio,Matt Damon,Jack Nicholson,Crime' 'Drama,2006-10-06,7
62,tt0338751,The Aviator,English,Germany,170,PG-13,77.0,110000000.0,Miramax,John Logan,NaN,Martin Scorsese,Leonardo DiCaprio,Cate Blanchett,Kate Beckinsale,Biography' 'Drama,2004-12-25,7
639,tt0993846,The Wolf of Wall Street,English,USA,180,R,75.0,100000000.0,Paramount Pictures,Terence Winter,Jordan Belfort,Martin Scorsese,Leonardo DiCaprio,Jonah Hill,Margot Robbie,Biography' 'Crime,2013-12-25,7
1611,NaN,Gangs of New York,English,USA,167,R,72.0,100000000.0,Miramax,Jay Cocks,Jay Cocks,Martin Scorsese,Leonardo DiCaprio,Cameron Diaz,Daniel Day-Lewis,Crime' 'Drama,2002-12-20,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,tt0277027,I Am Sam,English,USA,132,PG-13,28.0,22000000.0,New Line Cinema,Kristine Johnson,Jessie Nelson,Jessie Nelson,Sean Penn,Michelle Pfeiffer,Dakota Fanning,Drama,2002-01-25,1
438,tt0090863,The Color of Money,English,USA,119,R,77.0,13800000.0,Buena Vista Pictures,Walter Tevis,Richard Price,Martin Scorsese,Paul Newman,Tom Cruise,Mary Elizabeth Mastrantonio,Drama' 'Sport,1986-10-17,1
439,tt1454468,Gravity,English,UK,91,PG-13,96.0,100000000.0,Warner Bros.,Alfonso Cuarón,Jonás Cuarón,Alfonso Cuarón,Sandra Bullock,George Clooney,Ed Harris,Drama' 'Sci-Fi,2013-10-04,1
440,tt0113862,Mr. Holland's Opus,English,USA,143,PG,59.0,23000000.0,Buena Vista Pictures,Patrick Sheane Duncan,NaN,Stephen Herek,Richard Dreyfuss,Glenne Headly,Jay Thomas,Drama' 'Music,1996-01-19,1
1989,NaN,Wyatt Earp,English,USA,191,PG-13,47.0,63000000.0,Warner Bros.,Dan Gordon,Lawrence Kasdan,Lawrence Kasdan,Kevin Costner,Dennis Quaid,Gene Hackman,Adventure' 'Biography,1994-06-24,1

In [69]:
#Discovered some duplicates in the movie title gonna explore
oscars_df['movie title'].value_counts()

The Grandmaster                3
Little Women                   3
Searching for Bobby Fischer    3
Les Misérables                 3
Beginners                      3
                              ..
August: Osage County           1
Changeling                     1
Hannah and Her Sisters         1
Twister                        1
Never Look Away                1
Name: movie title, Length: 970, dtype: int64

*  Now I will do the same for the relationship between supporting actors 1 and 2 and director

In [70]:
oscars_df['Total_Movies_First_Supporting_Actor_Director'] =  oscars_df.groupby(['director','Supporting_Actor_1'])['Supporting_Actor_1'].transform('count')

In [71]:
oscars_df.sort_values('Total_Movies_First_Supporting_Actor_Director',ascending=False).head(10)

,IMDBId,movie title,language,country,runtime (mins),mpaarating,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre,release_date,Total_Movies_Lead_Actor_Director,Total_Movies_First_Supporting_Actor_Director
103,tt1229381,Hors la loi,French,France,138,R,59.0,NaN,Cohen Media Group,Rachid Bouchareb,Olivier Lorelle,Rachid Bouchareb,Jamel Debbouze,Roschdy Zem,Sami Bouajila,Crime' 'Drama,2010-09-22,2,4
1607,NaN,Spider-Man 2,English,USA,127,PG-13,83.0,200000000.0,Sony Pictures Home Entertainment,Stan Lee,Steve Ditko,Sam Raimi,Tobey Maguire,Kirsten Dunst,Alfred Molina,Action' 'Adventure,2004-06-30,4,4
942,tt0121766,Star Wars: Episode III - Revenge of the Sith,English,USA,140,PG-13,68.0,113000000.0,Twentieth Century Fox,George Lucas,NaN,George Lucas,Hayden Christensen,Natalie Portman,Ewan McGregor,Action' 'Adventure,2005-05-19,4,4
1360,NaN,The Ides of March,English,USA,101,R,67.0,12500000.0,Columbia Pictures,George Clooney,Grant Heslov,George Clooney,Paul Giamatti,George Clooney,Philip Seymour Hoffman,Drama' 'Thriller,2011-10-07,2,4
907,tt1124035,The Ides of March,English,USA,101,R,67.0,12500000.0,Columbia Pictures,George Clooney,Grant Heslov,George Clooney,Paul Giamatti,George Clooney,Philip Seymour Hoffman,Drama' 'Thriller,2011-10-07,2,4
444,tt0248667,Ali,English,USA,157,R,65.0,107000000.0,Columbia Pictures,Gregory Allen Howard,Stephen J. Rivele,Michael Mann,Will Smith,Jamie Foxx,Jon Voight,Biography' 'Drama,2001-12-25,2,4
1050,tt0316654,Spider-Man 2,English,USA,127,PG-13,83.0,200000000.0,Sony Pictures Home Entertainment,Stan Lee,Steve Ditko,Sam Raimi,Tobey Maguire,Kirsten Dunst,Alfred Molina,Action' 'Adventure,2004-06-30,4,4
1221,NaN,Hors la loi,French,France,138,R,59.0,NaN,Cohen Media Group,Rachid Bouchareb,Olivier Lorelle,Rachid Bouchareb,Jamel Debbouze,Roschdy Zem,Sami Bouajila,Crime' 'Drama,2010-09-22,2,4
1293,NaN,Days of Glory,French,Algeria,120,R,82.0,NaN,IFC Films,Rachid Bouchareb,Olivier Lorelle,Rachid Bouchareb,Samy Naceri,Roschdy Zem,Sami Bouajila,Action' 'Drama,2006-09-27,2,4
1425,NaN,Star Wars: Episode III - Revenge of the Sith,English,USA,140,PG-13,68.0,113000000.0,Twentieth Century Fox,George Lucas,NaN,George Lucas,Hayden Christensen,Natalie Portman,Ewan McGregor,Action' 'Adventure,2005-05-19,4,4

In [72]:
oscars_df['Total_Movies_Second_Supporting_Actor_Director'] =  oscars_df.groupby(['director','Supporting_Actor_2'])['Supporting_Actor_2'].transform('count')

In [73]:
oscars_df.sort_values('Total_Movies_Second_Supporting_Actor_Director',ascending=False).head(10)

,IMDBId,movie title,language,country,runtime (mins),mpaarating,metacritic score,budget,distributionCompany,writer1,writer2,director,Lead_Actor,Supporting_Actor_1,Supporting_Actor_2,genre,release_date,Total_Movies_Lead_Actor_Director,Total_Movies_First_Supporting_Actor_Director,Total_Movies_Second_Supporting_Actor_Director
1394,NaN,Moulin Rouge!,English,Australia,127,PG-13,66.0,50000000.0,Twentieth Century Fox,Baz Luhrmann,Craig Pearce,Baz Luhrmann,Nicole Kidman,Ewan McGregor,John Leguizamo,Drama' 'Musical,2001-06-01,2,2,4.0
188,tt0203009,Moulin Rouge!,English,Australia,127,PG-13,66.0,50000000.0,Twentieth Century Fox,Baz Luhrmann,Craig Pearce,Baz Luhrmann,Nicole Kidman,Ewan McGregor,John Leguizamo,Drama' 'Musical,2001-06-01,2,2,4.0
942,tt0121766,Star Wars: Episode III - Revenge of the Sith,English,USA,140,PG-13,68.0,113000000.0,Twentieth Century Fox,George Lucas,NaN,George Lucas,Hayden Christensen,Natalie Portman,Ewan McGregor,Action' 'Adventure,2005-05-19,4,4,4.0
1047,tt0117509,Romeo + Juliet,English,USA,120,PG-13,60.0,14500000.0,Twentieth Century Fox,William Shakespeare,Craig Pearce,Baz Luhrmann,Leonardo DiCaprio,Claire Danes,John Leguizamo,Drama' 'Romance,1996-11-01,2,2,4.0
569,tt0444182,Days of Glory,French,Algeria,120,R,82.0,NaN,IFC Films,Rachid Bouchareb,Olivier Lorelle,Rachid Bouchareb,Samy Naceri,Roschdy Zem,Sami Bouajila,Action' 'Drama,2006-09-27,2,4,4.0
1293,NaN,Days of Glory,French,Algeria,120,R,82.0,NaN,IFC Films,Rachid Bouchareb,Olivier Lorelle,Rachid Bouchareb,Samy Naceri,Roschdy Zem,Sami Bouajila,Action' 'Drama,2006-09-27,2,4,4.0
1062,tt0903624,The Hobbit: An Unexpected Journey,English,New Zealand,169,PG-13,58.0,180000000.0,Fathom Events,Fran Walsh,Philippa Boyens,Peter Jackson,Martin Freeman,Ian McKellen,Richard Armitage,Adventure' 'Fantasy,2012-12-14,2,3,4.0
1521,NaN,The Hobbit: The Desolation of Smaug,English,New Zealand,161,PG-13,66.0,225000000.0,Fathom Events,Fran Walsh,Philippa Boyens,Peter Jackson,Ian McKellen,Martin Freeman,Richard Armitage,Adventure' 'Fantasy,2013-12-13,2,2,4.0
85,tt1302006,The Irishman,English,USA,209,R,94.0,159000000.0,Netflix,Steven Zaillian,Charles Brandt,Martin Scorsese,Robert De Niro,Al Pacino,Joe Pesci,Biography' 'Crime,2019-11-27,5,1,4.0
1725,NaN,Star Wars: Episode II - Attack of the Clones,English,USA,142,PG,54.0,115000000.0,Twentieth Century Fox,George Lucas,Jonathan Hales,George Lucas,Hayden Christensen,Natalie Portman,Ewan McGregor,Action' 'Adventure,2002-05-16,4,4,4.0

In [74]:
oscars_df.shape

(1532, 20)

### Now I am going to create dummy variables for distribution company and genre
* First I will explore the distribution companies and the value counts for each

In [75]:
def get_top_ten(column):
    top_ten = oscars_df[column].value_counts().iloc[:10]
    mask = oscars_df[column].isin(top_ten.index)
    return mask

In [76]:
mask = get_top_ten('distributionCompany')

Filtering the distribution list to see how many of the studios were nominated for 4 or more oscars

In [77]:
oscars_df['distributionCompany'][mask].value_counts()

Paramount Pictures          130
Warner Bros.                122
Universal Pictures          115
Twentieth Century Fox       108
Columbia Pictures           107
Sony Pictures Classics      102
Miramax                      78
Buena Vista Pictures         56
Focus Features               48
Fox Searchlight Pictures     42
Name: distributionCompany, dtype: int64

In [78]:
distro_dummies = pd.get_dummies(oscars_df['distributionCompany'][mask])

In [79]:
oscars_df = pd.concat([oscars_df, distro_dummies], axis=1)

In [80]:
oscars_df.shape

(1532, 30)

In [81]:
oscars_df.head()

,IMDBId,movie title,language,country,runtime (mins),mpaarating,metacritic score,budget,distributionCompany,writer1,...,Buena Vista Pictures,Columbia Pictures,Focus Features,Fox Searchlight Pictures,Miramax,Paramount Pictures,Sony Pictures Classics,Twentieth Century Fox,Universal Pictures,Warner Bros.
0,tt0091763,Platoon,English,USA,120,R,92.0,6000000.0,Orion Pictures,Oliver Stone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tt0082979,Reds,English,USA,195,PG,76.0,32000000.0,Paramount Pictures,Warren Beatty,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,tt0084434,An Officer and a Gentleman,English,USA,124,R,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,tt0119360,In & Out,English,USA,90,PG-13,70.0,35000000.0,Paramount Pictures,Paul Rudnick,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,tt0292542,Son of the Bride,Spanish,Argentina,123,R,68.0,NaN,Sony Pictures Classics,Juan José Campanella,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

Now exploring genre and subgenres

In [82]:
oscars_df['genre'].value_counts()

Biography' 'Drama        194
Comedy' 'Drama           182
Crime' 'Drama            132
Drama                    128
Drama' 'Romance          109
                        ...
Documentary' 'History      1
Crime' 'Mystery            1
Comedy' 'Musical           1
Animation' 'Crime          1
Comedy' 'Music             1
Name: genre, Length: 73, dtype: int64

In [83]:
oscars_df['genre'].count()

1532

In [84]:
mask = get_top_ten('genre')
oscars_df['genre'][mask].value_counts()

Biography' 'Drama        194
Comedy' 'Drama           182
Crime' 'Drama            132
Drama                    128
Drama' 'Romance          109
Action' 'Adventure       108
Animation' 'Adventure     57
Adventure' 'Drama         37
Drama' 'History           36
Drama' 'Music             33
Name: genre, dtype: int64

In [85]:
main_genre_dummies = pd.get_dummies(oscars_df['genre'][mask])
oscars_df = pd.concat([oscars_df, main_genre_dummies], axis=1)

In [86]:
oscars_df.shape

(1532, 40)

In [87]:
oscars_df.columns

Index(['IMDBId', 'movie title', 'language', 'country', 'runtime (mins)',
       'mpaarating', 'metacritic score', 'budget', 'distributionCompany',
       'writer1', 'writer2', 'director', 'Lead_Actor', 'Supporting_Actor_1',
       'Supporting_Actor_2', 'genre', 'release_date',
       'Total_Movies_Lead_Actor_Director',
       'Total_Movies_First_Supporting_Actor_Director',
       'Total_Movies_Second_Supporting_Actor_Director', 'Buena Vista Pictures',
       'Columbia Pictures', 'Focus Features', 'Fox Searchlight Pictures',
       'Miramax', 'Paramount Pictures', 'Sony Pictures Classics',
       'Twentieth Century Fox', 'Universal Pictures', 'Warner Bros.',
       'Action' 'Adventure', 'Adventure' 'Drama', 'Animation' 'Adventure',
       'Biography' 'Drama', 'Comedy' 'Drama', 'Crime' 'Drama', 'Drama',
       'Drama' 'History', 'Drama' 'Music', 'Drama' 'Romance'],
      dtype='object')

In [88]:
#Drop duplicate columns from subgenre 1
oscars_df = oscars_df.loc[:,~oscars_df.columns.duplicated()]

In [89]:
oscars_df.shape

(1532, 40)

I won't do a join on subgenre_2 or 3 because the same genres are represented in the already present dummy variables

## Create a season column based off of the date time column

In [90]:
def get_season(column):
    month =  pd.DatetimeIndex(oscars_df[column]).month
    seasons_list = []
    for m in month:
        if m == 12 or m <= 3 :
            seasons_list.append('Winter')
        elif m <= 5 :
            seasons_list.append('Spring')
        elif m<= 8:
            seasons_list.append('Summer')
        else:
            seasons_list.append('Fall')
    return seasons_list

In [91]:
oscars_df['season'] = get_season('release_date')

In [92]:
oscars_df.season.value_counts()

Winter    664
Fall      447
Summer    287
Spring    134
Name: season, dtype: int64

Now that I have the seasons and the value counts I will create dummy variables and join then to the dataframe

In [93]:
season_dummies = pd.get_dummies(oscars_df['season'])

In [94]:
season_dummies

      Fall  Spring  Summer  Winter
0        0       0       0       1
1        0       0       0       1
2        0       0       1       0
3        1       0       0       0
4        0       0       1       0
...    ...     ...     ...     ...
1981     0       0       0       1
1984     0       0       0       1
1986     0       0       1       0
1987     1       0       0       0
1989     0       0       1       0

[1532 rows x 4 columns]

In [95]:
oscars_df

,IMDBId,movie title,language,country,runtime (mins),mpaarating,metacritic score,budget,distributionCompany,writer1,...,Adventure' 'Drama,Animation' 'Adventure,Biography' 'Drama,Comedy' 'Drama,Crime' 'Drama,Drama,Drama' 'History,Drama' 'Music,Drama' 'Romance,season
0,tt0091763,Platoon,English,USA,120,R,92.0,6000000.0,Orion Pictures,Oliver Stone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Winter
1,tt0082979,Reds,English,USA,195,PG,76.0,32000000.0,Paramount Pictures,Warren Beatty,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Winter
2,tt0084434,An Officer and a Gentleman,English,USA,124,R,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Summer
3,tt0119360,In & Out,English,USA,90,PG-13,70.0,35000000.0,Paramount Pictures,Paul Rudnick,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall
4,tt0292542,Son of the Bride,Spanish,Argentina,123,R,68.0,NaN,Sony Pictures Classics,Juan José Campanella,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,NaN,The Time Machine,English,USA,96,PG-13,42.0,80000000.0,DreamWorks Distribution,H.G. Wells,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Winter
1984,NaN,Monster,English,USA,109,R,74.0,8000000.0,Newmarket Films,Patty Jenkins,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Winter
1986,NaN,The Lion King,English,USA,118,PG,55.0,260000000.0,Walt Disney Studios Motion Pictures,Jeff Nathanson,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Summer
1987,NaN,Ford v Ferrari,English,USA,152,PG-13,81.0,97600000.0,Twentieth Century Fox,Jez Butterworth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall
1989,NaN,Wyatt Earp,English,USA,191,PG-13,47.0,63000000.0,Warner Bros.,Dan Gordon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Summer

In [96]:
oscars_df = pd.concat([oscars_df, season_dummies], axis=1)

In [97]:
oscars_df.shape

(1532, 45)

## I will explore the country and language columns and see if it is worth while to create dummy variables based on it

In [98]:
oscars_df['country'].value_counts()

USA                            959
UK                             220
France                          69
Germany                         29
Canada                          26
Spain                           18
Japan                           16
Italy                           15
Sweden                          14
Ireland                         13
Australia                       13
Denmark                         13
New Zealand                     12
Mexico                          11
China                            9
Poland                           8
Argentina                        7
Russia                           6
Belgium                          6
Switzerland                      5
Iran                             4
Palestine                        4
Austria                          4
Brazil                           4
Colombia                         4
West Germany                     3
Israel                           3
Hungary                          3
Hong Kong                        3
Czech Republic                   3
Chile                            3
Netherlands                      2
South Korea                      2
Algeria                          2
Malta                            2
India                            2
Estonia                          2
Finland                          2
South Africa                     2
Greece                           1
Cambodia                         1
United Arab Emirates             1
Taiwan                           1
Mauritania                       1
Lebanon                          1
Republic of North Macedonia      1
Norway                           1
Turkey                           1
Name: country, dtype: int64

In [99]:
oscars_df['language'].value_counts()

English       1293
French          49
Spanish         35
German          19
Japanese        18
Italian         12
Swedish         12
Arabic          11
Danish           8
Mandarin         8
Polish           6
Hindi            5
Persian          4
Flemish          4
Russian          4
Dutch            3
Portuguese       3
Hebrew           3
Norwegian        3
Hungarian        3
Czech            2
Korean           2
None             2
Turkish          2
Ukrainian        2
Tibetan          2
Estonian         2
Aramaic          2
Bengali          2
Finnish          2
Afrikaans        2
Latin            2
Mongolian        1
Greek            1
Zulu             1
Bosnian          1
Aboriginal       1
Name: language, dtype: int64

* Since both the country and language lean heavily towards AmericaN/English I will leave those alone as potential variables for now

## Now I will explore the actors and the number of nominations and see if there is a good cutoff for the number of nominations and a dummy variable

In [100]:
oscars_df['Lead_Actor'].value_counts()

Tom Hanks            23
Meryl Streep         21
Leonardo DiCaprio    20
Jeff Bridges         15
Brad Pitt            14
                     ..
Irène Jacob           1
Bob Hoskins           1
Joanna Kulig          1
Danny Aiello          1
Ivana Baquero         1
Name: Lead_Actor, Length: 581, dtype: int64

In [101]:
top_ten = oscars_df['Lead_Actor'].value_counts().iloc[:10]
mask = oscars_df['Lead_Actor'].isin(top_ten.index)

In [102]:
oscars_df['Lead_Actor'][mask].value_counts()

Tom Hanks            23
Meryl Streep         21
Leonardo DiCaprio    20
Jeff Bridges         15
Brad Pitt            14
Denzel Washington    13
Mel Gibson           13
Matt Damon           13
Johnny Depp          12
Paul Newman          11
Name: Lead_Actor, dtype: int64

For the creation of the dummy variable I will consider lead actors with 5 or more nominations

In [103]:
actor_dummies = pd.get_dummies(oscars_df['Lead_Actor'][mask])

In [104]:
oscars_df = pd.concat([oscars_df, actor_dummies], axis=1)

In [105]:
oscars_df.shape

(1532, 55)

In [106]:
vc = oscars_df['Supporting_Actor_1'].value_counts() 
mask = oscars_df['Supporting_Actor_1'].isin(vc[vc >= 5].index)

In [107]:
oscars_df['Supporting_Actor_1'][mask].value_counts()

Meryl Streep          13
Kate Winslet           9
Cate Blanchett         9
Matt Damon             9
Sissy Spacek           8
Julianne Moore         8
Glenn Close            8
Robin Williams         7
Ed Harris              7
Jessica Lange          7
Emma Thompson          7
George Clooney         7
Scarlett Johansson     7
Ben Kingsley           7
Alec Baldwin           6
Uma Thurman            6
Nicolas Cage           6
Anthony Hopkins        6
John Cusack            6
Geena Davis            6
Charlize Theron        6
Jeremy Irons           6
Nicole Kidman          6
Willem Dafoe           6
Michelle Pfeiffer      6
Jude Law               6
Colin Firth            6
Leonard Nimoy          5
Viggo Mortensen        5
Ralph Fiennes          5
Diane Lane             5
Samantha Morton        5
Laura Dern             5
Robert Duvall          5
Julia Roberts          5
Kurt Russell           5
Tommy Lee Jones        5
Jamie Foxx             5
Robert De Niro         5
Susan Sarandon         5
Karen Allen            5
Emma Watson            5
John Turturro          5
Aaron Eckhart          5
John Malkovich         5
Angelina Jolie         5
Heath Ledger           5
Name: Supporting_Actor_1, dtype: int64

In [108]:
vc = oscars_df['Supporting_Actor_2'].value_counts() 
mask = oscars_df['Supporting_Actor_2'].isin(vc[vc >= 5].index)

In [109]:
oscars_df['Supporting_Actor_2'][mask].value_counts()

Willem Dafoe           9
Christopher Plummer    9
Ed Harris              7
Robert De Niro         7
Margot Robbie          7
Kevin Bacon            7
Harvey Keitel          6
Alfred Molina          5
Joan Allen             5
Dianne Wiest           5
Catherine Keener       5
Scarlett Johansson     5
DeForest Kelley        5
Tom Wilkinson          5
Sigourney Weaver       5
Amy Adams              5
Michael Caine          5
Edward Norton          5
Marie-Josée Croze      5
Barbara Hershey        5
Name: Supporting_Actor_2, dtype: int64

## I will now explore the writers

In [110]:
oscars_df['writer1'].value_counts()

Woody Allen      16
Joel Coen        10
John Logan        9
Henry James       8
Aaron Sorkin      8
                 ..
Steve James       1
John McNamara     1
Gavin Hood        1
Tom Eyen          1
Louis Malle       1
Name: writer1, Length: 775, dtype: int64

In [111]:
oscars_df['writer2'].value_counts()

Ethan Coen              12
Ruth Prawer Jhabvala    11
Steven Zaillian          8
Philippa Boyens          6
Barry Levinson           5
                        ..
Daniela Capelato         1
Tracy Letts              1
Bráulio Mantovani        1
Aaron Covington          1
Richard Eyre             1
Name: writer2, Length: 630, dtype: int64

In [112]:
vc = oscars_df['writer1'].value_counts() 
mask = oscars_df['writer1'].isin(vc[vc >= 5].index)

In [113]:
oscars_df['writer1'][mask].value_counts()

Woody Allen             16
Joel Coen               10
John Logan               9
Anthony McCarten         8
Quentin Tarantino        8
Henry James              8
Lawrence Kasdan          8
Aaron Sorkin             8
Nora Ephron              7
Paul Thomas Anderson     7
Pedro Almodóvar          7
William Shakespeare      7
Lee Hall                 7
Melissa Mathison         6
Eric Roth                6
Nick Hornby              6
Peter Morgan             6
Fran Walsh               6
Tab Murphy               5
Oliver Stone             5
Steven Knight            5
Wim Wenders              5
Mike Leigh               5
Steven Zaillian          5
Christopher Nolan        5
Stephen King             5
Gene Roddenberry         5
John Lasseter            5
William Nicholson        5
Bob Kane                 5
Name: writer1, dtype: int64

In [114]:
vc = oscars_df['writer2'].value_counts() 
mask = oscars_df['writer2'].isin(vc[vc >= 5].index)

In [115]:
oscars_df['writer2'][mask].value_counts()

Ethan Coen              12
Ruth Prawer Jhabvala    11
Steven Zaillian          8
Philippa Boyens          6
Eric Roth                5
Anthony Minghella        5
Barry Levinson           5
William Goldman          5
Peter Weir               5
Tom Stoppard             5
Name: writer2, dtype: int64

I will create dummy variables for writer 1

In [116]:
writers_dummies = pd.get_dummies(oscars_df['writer1'][mask])

In [117]:
oscars_df = pd.concat([oscars_df, writers_dummies], axis=1)

In [118]:
oscars_df.shape

(1532, 86)

### Create dummies for ratings

In [119]:
oscars_df.mpaarating.value_counts()

R            749
PG-13        399
PG           272
Not Rated     47
G             42
Unrated        5
1h 48min       2
TV-MA          2
1h 54min       2
1h 30min       2
1h 46min       2
1h 56min       2
1h 34min       2
TV-14          1
1h 55min       1
2h 9min        1
2h 10min       1
Name: mpaarating, dtype: int64

In [120]:
top_six = oscars_df['mpaarating'].value_counts().iloc[:6]
mask = oscars_df['mpaarating'].isin(top_six.index)
ratings_dummies = pd.get_dummies(oscars_df['mpaarating'][mask])

In [121]:
oscars_df = pd.concat([oscars_df, ratings_dummies], axis=1)

In [122]:
oscars_df.shape

(1532, 92)

In [123]:
oscars_df

,IMDBId,movie title,language,country,runtime (mins),mpaarating,metacritic score,budget,distributionCompany,writer1,...,Tony Kushner,Valerie Curtin,William Goldman,Winston Groom,G,Not Rated,PG,PG-13,R,Unrated
0,tt0091763,Platoon,English,USA,120,R,92.0,6000000.0,Orion Pictures,Oliver Stone,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0
1,tt0082979,Reds,English,USA,195,PG,76.0,32000000.0,Paramount Pictures,Warren Beatty,...,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0
2,tt0084434,An Officer and a Gentleman,English,USA,124,R,75.0,7500000.0,Paramount Pictures,Douglas Day Stewart,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0
3,tt0119360,In & Out,English,USA,90,PG-13,70.0,35000000.0,Paramount Pictures,Paul Rudnick,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0
4,tt0292542,Son of the Bride,Spanish,Argentina,123,R,68.0,NaN,Sony Pictures Classics,Juan José Campanella,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,NaN,The Time Machine,English,USA,96,PG-13,42.0,80000000.0,DreamWorks Distribution,H.G. Wells,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0
1984,NaN,Monster,English,USA,109,R,74.0,8000000.0,Newmarket Films,Patty Jenkins,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0
1986,NaN,The Lion King,English,USA,118,PG,55.0,260000000.0,Walt Disney Studios Motion Pictures,Jeff Nathanson,...,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0
1987,NaN,Ford v Ferrari,English,USA,152,PG-13,81.0,97600000.0,Twentieth Century Fox,Jez Butterworth,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0
1989,NaN,Wyatt Earp,English,USA,191,PG-13,47.0,63000000.0,Warner Bros.,Dan Gordon,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0

## Now that I am done with exploring the datafram I will being exploring the features and regression

In [124]:
oscars_df.to_csv('oscar_movies_data.csv',encoding='utf-8-sig')