In [1]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import time, os
from time import sleep
from random import randint
import re
import json
from fake_useragent import UserAgent
import math

## Scrape imdb awards page

In [2]:
ua = UserAgent()
user_agent = {'User-agent': ua.random}
pages = np.arange(1980,2021)
#title_ids=[]
def get_title_ids(pages):
    imdb_ids=[]
    #Get all the raw title ids
    for page in pages:
        url = 'https://www.imdb.com/event/ev0000003/'+str(page)
        response = requests.get(url,headers=user_agent).text
        data = json.loads( re.findall(r'IMDbReactWidgets\.NomineesWidget\.push.*?(\{.*\})', response)[0] )

        #print(json.dumps(data, indent=4)) # <-- comment this out to print all data

        for award in data['nomineesWidgetModel']['eventEditionSummary']['awards']:
            if award['awardName'] != 'Oscar':
                continue
            for title in award['categories']:
                noms = title['nominations']
                for nom in noms:
                    if len(nom['secondaryNominees'])!=0:
                        id_ = nom['secondaryNominees'][0]['const']
                    else:
                        id_ = nom['primaryNominees'][0]['const']
                    imdb_ids.append(id_)
        sleep(randint(2,10))
        
    #change the titleId into a set
    imdb_ids_set = set(imdb_ids)
    imdb_film_ids = []
    
    #Set Contains id for people and films extract the films only 
    for film_id in imdb_ids_set:
        if film_id[0]=='t':
            imdb_film_ids.append(film_id)
    return imdb_film_ids

## Scrape from IMDB Title Film Page

In [3]:
def get_movie_crew_and_genre(soup,field_name):
    '''Function to grab films writers,genres,directors,and '''
    movie_crew_list = []
    for a in soup.find('h4', text=re.compile(field_name)).parent.find_all('a'):
        movie_crew_list.append(a.text.strip())
    return movie_crew_list

In [4]:
def get_movie_value(soup, field_name):
    
    '''Grab a value from Box Office Mojo HTML
    
    Takes a string attribute of a movie on the page and returns the string in
    the next sibling object (the value for that attribute) or None if nothing is found.
    '''
    
    obj = soup.find(text=re.compile(field_name))
    
    if not obj: 
        return None
    
    # this works for most of the values
    next_element = obj.findNext()
    
    if next_element:
        return next_element.text 
    else:
        return None

In [5]:
def get_distribution_company(soup):
    usa_distribution = ''
    usa_distribution_and_release = []
    distribution_company = soup.find('h4', {'id':'distributors'}).parent.find_all('li')
    for country_distro in distribution_company:
        if 'USA' in country_distro.text:
            usa_distribution = country_distro.text
            break
    usa_distribution_and_release = usa_distribution.split('(')
    usa_distribution = usa_distribution_and_release[0].replace('\n','').strip()
    return usa_distribution

In [42]:
def get_movie_dict(titleId):
    '''
    Grab the titleId 
    '''
    
    url = 'https://www.imdb.com/title/'+str(titleId)
    response = requests.get(url)
    page = response.text
    soup = BeautifulSoup(page, "lxml")
    
    title_div = soup.find('div',class_='title_wrapper')
    title_div

    IMDB_id = titleId
    
    #title 
    title = get_movie_value(soup,'title')
    title = title.split('(')[0].strip()

    #Get the directors for the movie
    directors = get_movie_crew_and_genre(soup,'Director')


    #get the writers for the movie
    writers = get_movie_crew_and_genre(soup,'Writer')

    #get the cast of the movie:
    casts = get_movie_crew_and_genre(soup,'Stars')
    casts = casts[0:3]

    #genre
    genres = get_movie_crew_and_genre(soup,'Genres')

    #country 
    country = get_movie_crew_and_genre(soup,'Country')
    country = country[0]

    #language
    language = get_movie_crew_and_genre(soup,'Language')
    language = language[0]

    #runtime
    runtime = title_div.find('time').text
    runtime = "".join(time.strip() for time in runtime.split("\n"))
#     try:
#         converted_runtime = int(runtime.split()[0])
#     except:
#         converted_runtime = 0

    #rating
    release_and_rating_string = title_div.find('div',{'class':'subtext'}).text
    rating = release_and_rating_string.split('|')[0].strip()
    rating

    #Release Date
    release_and_rating_string = title_div.find('div',{'class':'subtext'}).text
    try:
        release = release_and_rating_string.split('|')[3].strip()
        release = release.split('(')
        release = release[0]
    except:
        release = math.nan
    #converted_release_date = to_date(release_date)

    #Get budget
    try:
        budget = soup.find('h4', text=re.compile('Budget')).parent.text
        budget = budget.split('\n')
        budget = budget[1].split('$')
        budget = budget[1].replace(',','')
        budget = int(budget) 
    except:
        budget = math.nan


    #metacritic score
    try:
        metacritic_score = soup.find('div',{'class':'titleReviewBar'}).span.text
    except:
         metacritic_score = math.nan
    try:
        metacritic_score = int(metacritic_score)
    except:
        metacritic_score = math.nan
    
    headers = ['IMDBId','movie title','director(s)','writer(s)','casts','genre(s)','language','country',
           'runtime (mins)', 'mpaarating', 'release date','metacritic score','budget']

    movie_data = []
    movie_dict = dict(zip(headers, [IMDB_id,
                                    title,
                                    directors,
                                    writers,
                                    casts,
                                    genres,
                                    language,
                                    country,
                                    runtime,
                                    rating,
                                    release,
                                    metacritic_score,
                                    budget]))

    #movie_data.append(movie_dict)
    sleep(randint(2,10))
    return movie_dict

In [43]:
def get_distribution_dict(titleId):
    
    url = 'https://www.imdb.com/title/'+str(titleId)+'/companycredits'
    response = requests.get(url)
    page = response.text
    soup = BeautifulSoup(page, "lxml")

    IMDB_id = titleId
    distribution_company = get_distribution_company(soup)

    headers = ['IMDBId','distributionCompany']

    #distribution_data = []
    distribution_dict = dict(zip(headers, [IMDB_id,
                                    distribution_company]))

    #distribution_data.append(distribution_dict)
    sleep(randint(2,10))
    return distribution_dict

In [29]:
import pandas as pd
links = get_title_ids(pages)

KeyboardInterrupt:

In [30]:
print(links)

['tt0091763', 'tt0082979', 'tt0084434', 'tt0119360', 'tt0292542', 'tt1069238', 'tt0108550', 'tt0082736', 'tt0090203', 'tt0087027', 'tt0094924', 'tt1403865', 'tt0093010', 'tt2267998', 'tt0120863', 'tt0095530', 'tt4048272', 'tt0280778', 'tt0091167', 'tt1276419', 'tt1619029', 'tt0368794', 'tt0247196', 'tt8991268', 'tt0106226', 'tt8404614', 'tt0106977', 'tt2011971', 'tt0084805', 'tt0111797', 'tt1568346', 'tt0082158', 'tt1007029', 'tt0477302', 'tt0107943', 'tt2582802', 'tt0084917', 'tt2852470', 'tt0124207', 'tt2543164', 'tt2106476', 'tt0166943', 'tt0253474', 'tt0465551', 'tt0387131', 'tt0095276', 'tt0106332', 'tt2562232', 'tt2084970', 'tt0390221', 'tt0465538', 'tt0097322', 'tt0441909', 'tt1065073', 'tt0108101', 'tt2059255', 'tt0935075', 'tt0108149', 'tt0082853', 'tt0119815', 'tt0092593', 'tt3553976', 'tt0338751', 'tt1907668', 'tt7349662', 'tt0467406', 'tt0094828', 'tt0454876', 'tt0959337', 'tt6751668', 'tt0081375', 'tt0078754', 'tt0086450', 'tt0101410', 'tt0085244', 'tt0361748', 'tt0452623', 'tt0096028', 'tt1535109', 'tt3741834', 'tt1084950', 'tt0104928', 'tt0338135', 'tt0775529', 'tt1013753', 'tt1302006', 'tt0084874', 'tt2305051', 'tt0088939', 'tt0101811', 'tt0870111', 'tt0081568', 'tt0089276', 'tt0080549', 'tt4648786', 'tt0813547', 'tt4555426', 'tt0113720', 'tt0092804', 'tt1790885', 'tt0081656', 'tt8075192', 'tt0114212', 'tt1229381', 'tt1820488', 'tt0089643', 'tt0078788', 'tt0099674', 'tt0116410', 'tt0408306', 'tt0104797', 'tt0414387', 'tt0117589', 'tt0887912', 'tt0114746', 'tt1950186', 'tt0758758', 'tt0190332', 'tt0089360', 'tt5580390', 'tt1291584', 'tt6304162', 'tt0113627', 'tt0175880', 'tt0086423', 'tt0093067', 'tt1532503', 'tt0180093', 'tt0107617', 'tt0094056', 'tt0174856', 'tt0380510', 'tt0111495', 'tt0375679', 'tt0098384', 'tt0401383', 'tt0095606', 'tt0083732', 'tt0120586', 'tt0265086', 'tt0085370', 'tt0322674', 'tt0118607', 'tt0106881', 'tt0443489', 'tt0172396', 'tt0127536', 'tt4034228', 'tt0104046', 'tt0120324', 'tt0094027', 'tt0287467', 'tt0095243', 'tt0318374', 'tt0099902', 'tt4846340', 'tt0120737', 'tt0082222', 'tt0075975', 'tt2125435', 'tt0100935', 'tt0083922', 'tt3513548', 'tt0100486', 'tt0097937', 'tt5776858', 'tt2671706', 'tt1255953', 'tt0099566', 'tt0098319', 'tt0842926', 'tt0918927', 'tt3716530', 'tt1655442', 'tt0445620', 'tt0090557', 'tt0095497', 'tt0089841', 'tt0090886', 'tt0088172', 'tt0097243', 'tt0443272', 'tt0104454', 'tt0140352', 'tt0257360', 'tt1120985', 'tt1454029', 'tt0085478', 'tt0203009', 'tt0468569', 'tt3783958', 'tt0134119', 'tt0102926', 'tt3841424', 'tt4550098', 'tt0107156', 'tt0078841', 'tt0080009', 'tt0363163', 'tt0100049', 'tt5311542', 'tt0311648', 'tt0243155', 'tt0091538', 'tt0116790', 'tt1417075', 'tt0090329', 'tt0257044', 'tt0947798', 'tt0104952', 'tt2980516', 'tt0113158', 'tt0101889', 'tt0095159', 'tt0418773', 'tt0790712', 'tt0083987', 'tt0498380', 'tt1135503', 'tt0211915', 'tt0099348', 'tt0102138', 'tt0455590', 'tt1174732', 'tt0443446', 'tt0106918', 'tt0091530', 'tt0083226', 'tt2024544', 'tt7131622', 'tt0824758', 'tt0824747', 'tt0097766', 'tt0468565', 'tt0120776', 'tt0372824', 'tt0107818', 'tt1340800', 'tt5607714', 'tt0087003', 'tt0325710', 'tt0116754', 'tt0117477', 'tt0094947', 'tt0208874', 'tt0113819', 'tt0086561', 'tt0095675', 'tt5639354', 'tt0115988', 'tt0203119', 'tt0101507', 'tt1010048', 'tt0107207', 'tt0082971', 'tt0120382', 'tt3224458', 'tt0103939', 'tt1100089', 'tt0138097', 'tt0079948', 'tt0093664', 'tt0108052', 'tt0375063', 'tt0086312', 'tt0120520', 'tt0106966', 'tt6966692', 'tt0407887', 'tt0408236', 'tt0209037', 'tt0114808', 'tt0078875', 'tt0112818', 'tt0279064', 'tt0093209', 'tt0077288', 'tt0489327', 'tt0970179', 'tt3460252', 'tt0090605', 'tt0087699', 'tt5027774', 'tt0104257', 'tt0108122', 'tt0090756', 'tt0169102', 'tt0443680', 'tt0085461', 'tt0120684', 'tt0181865', 'tt0171804', 'tt0091738', 'tt0104403', 'tt0399146', 'tt0089424', 'tt3203606', 'tt0117666', 'tt1173745', 'tt3966404', 'tt0104348', 'tt0078868', 'tt3682448', 'tt0338309', 'tt0109771', 'tt0095647', 'tt1895587', 'tt0080798', 'tt0472062', 'tt0101902', 'tt0092569', 'tt0383694', 'tt0978759', 'tt0117631', 'tt0103791', 'tt0308644', 'tt0117050', 'tt1853728', 'tt0089755', 'tt1045658', 'tt0315983', 'tt0080678', 'tt0096969', 'tt0079417', 'tt1149362', 'tt0340012', 'tt0405159', 'tt2737050', 'tt0119396', 'tt0245157', 'tt0083967', 'tt0450188', 'tt0258068', 'tt0085380', 'tt1504320', 'tt0118849', 'tt0084136', 'tt0875034', 'tt0158302', 'tt0105151', 'tt0097123', 'tt0388795', 'tt0457655', 'tt0335266', 'tt4669986', 'tt6294822', 'tt0449467', 'tt0093713', 'tt0325980', 'tt1399683', 'tt0280707', 'tt8649186', 'tt0089881', 'tt1185616', 'tt0478304', 'tt1866249', 'tt1613750', 'tt6000478', 'tt0497465', 'tt0112384', 'tt4285496', 'tt7048622', 'tt0234288', 'tt0120633', 'tt0328538', 'tt0104036', 'tt0082096', 'tt2584384', 'tt0083866', 'tt0093389', 'tt0079696', 'tt0250797', 'tt0085297', 'tt2718492', 'tt0790636', 'tt2278388', 'tt2119532', 'tt0099422', 'tt0111579', 'tt0090830', 'tt0112579', 'tt0119822', 'tt0102571', 'tt0419279', 'tt0288330', 'tt0116999', 'tt0107822', 'tt0110638', 'tt0120815', 'tt1596363', 'tt0264464', 'tt1033575', 'tt0119164', 'tt0217505', 'tt0118799', 'tt0086197', 'tt0082206', 'tt0120274', 'tt0180073', 'tt0477348', 'tt0436697', 'tt0094606', 'tt1560747', 'tt5083738', 'tt0105328', 'tt1478338', 'tt0311519', 'tt2179136', 'tt4239726', 'tt0079625', 'tt1542344', 'tt0416044', 'tt0183659', 'tt7549996', 'tt0086429', 'tt0110367', 'tt0078902', 'tt1210166', 'tt0161860', 'tt0085767', 'tt0120689', 'tt0878804', 'tt0097239', 'tt0109348', 'tt0090576', 'tt0101921', 'tt0369339', 'tt0112573', 'tt0088811', 'tt1832382', 'tt6543652', 'tt0104774', 'tt0095953', 'tt0352248', 'tt0117364', 'tt0311113', 'tt0277027', 'tt0102426', 'tt0090863', 'tt1454468', 'tt0113862', 'tt6155172', 'tt0093004', 'tt0082970', 'tt0248667', 'tt0117817', 'tt0110684', 'tt3316960', 'tt0172493', 'tt0092699', 'tt0274558', 'tt0093668', 'tt0150915', 'tt0338013', 'tt0327056', 'tt0114388', 'tt0112379', 'tt0120338', 'tt0079054', 'tt4595882', 'tt0105695', 'tt0117318', 'tt7286456', 'tt1655420', 'tt1392190', 'tt0116695', 'tt0089716', 'tt0424205', 'tt0765432', 'tt0405094', 'tt0119448', 'tt0111454', 'tt0079579', 'tt4080728', 'tt2334873', 'tt0081150', 'tt0100405', 'tt0079522', 'tt0102753', 'tt0097276', 'tt0488478', 'tt0084591', 'tt0090223', 'tt1235166', 'tt3808342', 'tt0449059', 'tt0110932', 'tt0139654', 'tt0110882', 'tt0093105', 'tt0104237', 'tt0092603', 'tt0079239', 'tt0087091', 'tt0976051', 'tt1800241', 'tt0185125', 'tt0109446', 'tt2431286', 'tt0109830', 'tt0083543', 'tt0879843', 'tt0115751', 'tt0118564', 'tt0245712', 'tt0475276', 'tt0100395', 'tt0395169', 'tt0100200', 'tt0167260', 'tt0120601', 'tt0092584', 'tt1057500', 'tt0110880', 'tt0091886', 'tt1313092', 'tt0113987', 'tt0104756', 'tt1517451', 'tt2852406', 'tt8579674', 'tt0119942', 'tt7125860', 'tt0458352', 'tt0078718', 'tt5726616', 'tt0102713', 'tt1322269', 'tt2080374', 'tt0101516', 'tt0090257', 'tt1649419', 'tt0090206', 'tt0081398', 'tt0783233', 'tt3076658', 'tt3659388', 'tt0241303', 'tt0087538', 'tt3750872', 'tt1663202', 'tt0104466', 'tt1077262', 'tt0124315', 'tt0093277', 'tt6938828', 'tt0433383', 'tt0468489', 'tt0109707', 'tt0147004', 'tt0240200', 'tt0094291', 'tt0176415', 'tt0102619', 'tt0450259', 'tt0088322', 'tt0100557', 'tt0094142', 'tt0765443', 'tt0942385', 'tt1707386', 'tt0499549', 'tt0285742', 'tt0110877', 'tt0096018', 'tt0078952', 'tt0964517', 'tt0382330', 'tt0107206', 'tt0444182', 'tt0362269', 'tt0421715', 'tt0112431', 'tt0395972', 'tt0758732', 'tt0369702', 'tt0109306', 'tt2381111', 'tt0087553', 'tt0216787', 'tt2991224', 'tt1821549', 'tt0101587', 'tt0091867', 'tt0351817', 'tt0082280', 'tt0379725', 'tt0457430', 'tt0084855', 'tt0084865', 'tt0089941', 'tt0166896', 'tt0116209', 'tt0181875', 'tt2402927', 'tt0410097', 'tt0088007', 'tt0210727', 'tt0089748', 'tt0088933', 'tt0313196', 'tt2358891', 'tt0089606', 'tt0172495', 'tt0114814', 'tt1193138', 'tt0114287', 'tt1821593', 'tt2024519', 'tt1315981', 'tt0117057', 'tt0358273', 'tt0087781', 'tt0810819', 'tt0116282', 'tt0090110', 'tt0247425', 'tt0298845', 'tt0100470', 'tt5294550', 'tt0085213', 'tt0082031', 'tt0857191', 'tt0118749', 'tt0104765', 'tt1379182', 'tt0120090', 'tt0080979', 'tt1206488', 'tt0119488', 'tt5186714', 'tt0117381', 'tt0105107', 'tt0112641', 'tt4995790', 'tt0118566', 'tt6266538', 'tt0414055', 'tt0094737', 'tt0993846', 'tt0099077', 'tt0095765', 'tt0105323', 'tt0086425', 'tt0454921', 'tt0097441', 'tt1340107', 'tt0091217', 'tt0140888', 'tt0350258', 'tt0087365', 'tt0088213', 'tt3544082', 'tt1727824', 'tt0079517', 'tt0090985', 'tt1164999', 'tt0081414', 'tt3281548', 'tt0120885', 'tt0082095', 'tt0116692', 'tt0094315', 'tt6394270', 'tt0478134', 'tt0119217', 'tt0081974', 'tt5580036', 'tt0298228', 'tt0299977', 'tt1125849', 'tt0082416', 'tt0084707', 'tt0283509', 'tt0365737', 'tt1605783', 'tt0100211', 'tt0120402', 'tt0166924', 'tt0096316', 'tt0159365', 'tt0100389', 'tt0104507', 'tt0103176', 'tt0195685', 'tt2180411', 'tt0203230', 'tt0088683', 'tt3830162', 'tt1445520', 'tt0158371', 'tt5649144', 'tt0167404', 'tt1602620', 'tt0086617', 'tt1602098', 'tt0086879', 'tt0181830', 'tt1554091', 'tt0084335', 'tt0078872', 'tt0413015', 'tt0162222', 'tt0083642', 'tt0469494', 'tt4136084', 'tt0317248', 'tt2802154', 'tt0080610', 'tt0097635', 'tt0119280', 'tt0101526', 'tt0337741', 'tt10199590', 'tt0079638', 'tt0087892', 'tt0426578', 'tt8291806', 'tt0097499', 'tt0110428', 'tt2396589', 'tt0090554', 'tt0407265', 'tt0094226', 'tt0097165', 'tt7653254', 'tt3011894', 'tt0091554', 'tt0340855', 'tt0090563', 'tt1068646', 'tt0376541', 'tt3170902', 'tt0169547', 'tt0084370', 'tt0081283', 'tt0120255', 'tt0491747', 'tt0088090', 'tt0268126', 'tt0118632', 'tt1285016', 'tt0080928', 'tt0268978', 'tt4975722', 'tt0099685', 'tt0181530', 'tt0087932', 'tt0103074', 'tt1305806', 'tt0108551', 'tt0299658', 'tt0297884', 'tt1872194', 'tt8267604', 'tt2582782', 'tt0120679', 'tt0087921', 'tt0929632', 'tt0098067', 'tt0249462', 'tt0078966', 'tt2446980', 'tt0101640', 'tt0093565', 'tt1024648', 'tt4925292', 'tt3409392', 'tt0099703', 'tt0840361', 'tt0404203', 'tt0080388', 'tt0161023', 'tt0082846', 'tt0765429', 'tt5052448', 'tt0101540', 'tt0096463', 'tt0095593', 'tt0086992', 'tt0110912', 'tt0087144', 'tt3170832', 'tt0079826', 'tt0097216', 'tt0088146', 'tt5013056', 'tt0099334', 'tt0099653', 'tt0111161', 'tt0315733', 'tt1263670', 'tt0189998', 'tt0094608', 'tt0097155', 'tt0100157', 'tt0086619']

In [46]:
distribution_list = []
oscar_movie_list = []
movie_link_not_working = []
distro_link_not_working = []
count=0
for link in links:
    print(count)
    count+=1
    try:
        get_movie_dict(link)
        oscar_movie_list.append(get_movie_dict(link))
    except:
        movie_link_not_working.append(link)
    try:
        get_distribution_dict(link)
        distribution_list.append(get_distribution_dict(link))
    except:
        distro_link_not_working.append(link)
    
print(len(movie_link_not_working))
print(len(distro_link_not_working))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
0
1

In [47]:
movies_info_df = pd.DataFrame(oscar_movie_list)
movies_info_df.set_index('IMDBId', inplace=True)
movies_info_df.head()

,movie title,director(s),writer(s),casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget
IMDBId,,,,,,,,,,,,
tt0091763,Platoon,[Oliver Stone],[Oliver Stone],"[Charlie Sheen, Tom Berenger, Willem Dafoe]","[Drama, War]",English,USA,2h,R,6 February 1987,92.0,6000000.0
tt0082979,Reds,[Warren Beatty],"[Warren Beatty, Trevor Griffiths]","[Warren Beatty, Diane Keaton, Edward Herrmann]","[Biography, Drama, History, Romance]",English,USA,3h 15min,PG,25 December 1981,76.0,32000000.0
tt0084434,An Officer and a Gentleman,[Taylor Hackford],[Douglas Day Stewart],"[Richard Gere, Debra Winger, David Keith]","[Drama, Romance]",English,USA,2h 4min,R,13 August 1982,75.0,7500000.0
tt0119360,In & Out,[Frank Oz],[Paul Rudnick],"[Kevin Kline, Joan Cusack, Tom Selleck]","[Comedy, Romance]",English,USA,1h 30min,PG-13,19 September 1997,70.0,35000000.0
tt0292542,Son of the Bride,[Juan José Campanella],"[Juan José Campanella, Fernando Castets]","[Ricardo Darín, Héctor Alterio, Norma Aleandro]","[Comedy, Drama]",Spanish,Argentina,2h 3min,R,16 August 2001,68.0,NaN

In [48]:
movies_info_df.describe()

       metacritic score        budget
count        666.000000  5.460000e+02
mean          75.860360  2.749871e+07
std           11.386974  3.039982e+07
min           28.000000  1.800000e+05
25%           68.000000  8.100000e+06
50%           77.000000  1.800000e+07
75%           84.000000  3.237500e+07
max          100.000000  2.370000e+08

,movie title,director(s),writer(s),casts,genre(s),language,country,runtime (mins),mpaarating,release date,metacritic score,budget
IMDBId,,,,,,,,,,,,
tt0091763,False,False,False,False,False,False,False,False,False,False,False,False
tt0082979,False,False,False,False,False,False,False,False,False,False,False,False
tt0084434,False,False,False,False,False,False,False,False,False,False,False,False
tt0119360,False,False,False,False,False,False,False,False,False,False,False,False
tt0292542,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
tt0189998,False,False,False,False,False,False,False,False,False,False,False,False
tt0094608,False,False,False,False,False,False,False,False,False,False,False,False
tt0097155,False,False,False,False,False,False,False,False,False,True,True,True
tt0100157,False,False,False,False,False,False,False,False,False,False,False,False
tt0086619,False,False,False,False,False,False,False,False,False,False,False,False

In [45]:
len(oscar_movie_list)

362

In [54]:
#Create a distribution list data frame
distribution_info_df = pd.DataFrame(distribution_list)
distribution_info_df.set_index('IMDBId', inplace=True)
distribution_info_df

                           distributionCompany
IMDBId
tt0091763                       Orion Pictures
tt0082979                   Paramount Pictures
tt0084434                   Paramount Pictures
tt0119360                   Paramount Pictures
tt0292542               Sony Pictures Classics
...                                        ...
tt0189998  Lions Gate Films Home Entertainment
tt0094608                   Paramount Pictures
tt0097155                   Pathé-Nordisk Film
tt0100157                    Columbia Pictures
tt0086619         MGM/UA Entertainment Company

[796 rows x 1 columns]

In [57]:
distribution_info_df.tail()

                           distributionCompany
IMDBId
tt0189998  Lions Gate Films Home Entertainment
tt0094608                   Paramount Pictures
tt0097155                   Pathé-Nordisk Film
tt0100157                    Columbia Pictures
tt0086619         MGM/UA Entertainment Company

In [60]:
movies_info_df2 = pd.merge(movies_info_df, distribution_info_df, on='IMDBId', how='left')

movies_info_df2.shape

(797, 13)

In [63]:
movies_info_df2.to_csv('oscar_movies.csv',encoding='utf-8-sig')