In [16]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso,LassoCV,LinearRegression
from sklearn.preprocessing import StandardScaler

## Explore the data

In [3]:
oscars_df = pd.read_csv('oscar_movies_data_2.csv')

In [4]:
oscars_df.head()

,Unnamed: 0,IMDBId,movie title,language,country,runtime (mins),mpaarating,metacritic score,budget,distributionCompany,...,R,Unrated,Writer_Aaron Sorkin,Writer_Joel Coen,Writer_John Logan,Writer_Lawrence Kasdan,Writer_Paul Thomas Anderson,Writer_Pedro Almodóvar,Writer_Quentin Tarantino,Writer_Woody Allen
0,0,tt0091763,Platoon,English,USA,120,R,92.0,6.000000e+06,Orion Pictures,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,tt0082979,Reds,English,USA,195,PG,76.0,3.200000e+07,Paramount Pictures,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,tt0084434,An Officer and a Gentleman,English,USA,124,R,75.0,7.500000e+06,Paramount Pictures,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,tt0119360,In & Out,English,USA,90,PG-13,70.0,3.500000e+07,Paramount Pictures,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,tt0292542,Son of the Bride,Spanish,Argentina,123,R,68.0,1.136429e+07,Sony Pictures Classics,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
numerics = ['int16','int32','int64','float16','float32','float64']
numerical_vars = list(oscars_df.select_dtypes(include=numerics).columns)
oscars_data = oscars_df[numerical_vars]
oscars_data.shape

(1136, 88)

In [6]:
oscars_data.fillna(0,inplace=True)

/Users/sibongiletoure/anaconda3/envs/metis/lib/python3.8/site-packages/pandas/core/frame.py:4316: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [7]:
oscars_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1136 entries, 0 to 1135
Data columns (total 88 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Unnamed: 0                                               1136 non-null   int64
 1   runtime (mins)                                           1136 non-null   int64
 2   metacritic score                                         1136 non-null   float64
 3   budget                                                   1136 non-null   float64
 4   Total_Noms                                               1136 non-null   int64
 5   Director_Avg_Score                                       1136 non-null   float64
 6   Total_Director_Movies                                    1136 non-null   int64
 7   Lead_Actor_Avg_Score                                     1136 non-null   float64
 8   Total_Movies_Lead_Actor                                  1136 non-null   int64
 9   Avg_Rating_by_Genre                                      1136 non-null   float64
 10  Buena Vista Pictures                                     1136 non-null   float64
 11  Columbia Pictures                                        1136 non-null   float64
 12  Fox Searchlight Pictures                                 1136 non-null   float64
 13  Miramax                                                  1136 non-null   float64
 14  Paramount Pictures                                       1136 non-null   float64
 15  Sony Pictures Classics                                   1136 non-null   float64
 16  Twentieth Century Fox                                    1136 non-null   float64
 17  Universal Pictures                                       1136 non-null   float64
 18  Walt Disney Studios Motion Pictures                      1136 non-null   float64
 19  Warner Bros.                                             1136 non-null   float64
 20  Genre_Action                                             1136 non-null   float64
 21  Genre_Adventure                                          1136 non-null   float64
 22  Genre_Animation                                          1136 non-null   float64
 23  Genre_Biography                                          1136 non-null   float64
 24  Genre_Comedy                                             1136 non-null   float64
 25  Genre_Crime                                              1136 non-null   float64
 26  Genre_Documentary                                        1136 non-null   float64
 27  Genre_Drama                                              1136 non-null   float64
 28  Genre_Family                                             1136 non-null   float64
 29  Genre_Horror                                             1136 non-null   float64
 30  Subgenre_Adventure                                       1136 non-null   float64
 31  Subgenre_Comedy                                          1136 non-null   float64
 32  Subgenre_Crime                                           1136 non-null   float64
 33  Subgenre_Drama                                           1136 non-null   float64
 34  Subgenre_Fantasy                                         1136 non-null   float64
 35  Subgenre_History                                         1136 non-null   float64
 36  Subgenre_Music                                           1136 non-null   float64
 37  Subgenre_Mystery                                         1136 non-null   float64
 38  Subgenre_Romance                                         1136 non-null   float64
 39  Subgenre_Thriller                                        1136 non-null   float64
 40  Director_Barry Levinson                                  1136 non-null   float64
 41  Director_Clint Eastwood                                  1136 non-null   float64
 42  Director_Martin Scorsese                                 1136 non-null   float64
 43  Director_Ridley Scott                                    1136 non-null   float64
 44  Director_Robert Zemeckis                                 1136 non-null   float64
 45  Director_Ron Howard                                      1136 non-null   float64
 46  Director_Stephen Frears                                  1136 non-null   float64
 47  Director_Steven Spielberg                                1136 non-null   float64
 48  Director_Tim Burton                                      1136 non-null   float64
 49  Director_Woody Allen                                     1136 non-null   float64
 50  Lead_Actor_Brad Pitt                                     1136 non-null   float64
 51  Lead_Actor_Harrison Ford                                 1136 non-null   float64
 52  Lead_Actor_Johnny Depp                                   1136 non-null   float64
 53  Lead_Actor_Leonardo DiCaprio                             1136 non-null   float64
 54  Lead_Actor_Meryl Streep                                  1136 non-null   float64
 55  Lead_Actor_Robert De Niro                                1136 non-null   float64
 56  Lead_Actor_Robert Downey Jr.                             1136 non-null   float64
 57  Lead_Actor_Robin Williams                                1136 non-null   float64
 58  Lead_Actor_Tom Cruise                                    1136 non-null   float64
 59  Lead_Actor_Tom Hanks                                     1136 non-null   float64
 60  Awards_Best Actor in a Leading Role                      1136 non-null   float64
 61  Awards_Best Actor in a Supporting Role                   1136 non-null   float64
 62  Awards_Best Actress in a Leading Role                    1136 non-null   float64
 63  Awards_Best Actress in a Supporting Role                 1136 non-null   float64
 64  Awards_Best Art Direction-Set Decoration                 1136 non-null   float64
 65  Awards_Best Foreign Language Film                        1136 non-null   float64
 66  Awards_Best Foreign Language Film of the Year            1136 non-null   float64
 67  Awards_Best Motion Picture of the Year                   1136 non-null   float64
 68  Awards_Best Music, Original Song                         1136 non-null   float64
 69  Awards_Best Performance by an Actress in a Leading Role  1136 non-null   float64
 70  Fall                                                     1136 non-null   int64
 71  Spring                                                   1136 non-null   int64
 72  Summer                                                   1136 non-null   int64
 73  Winter                                                   1136 non-null   int64
 74  G                                                        1136 non-null   int64
 75  Not Rated                                                1136 non-null   int64
 76  PG                                                       1136 non-null   int64
 77  PG-13                                                    1136 non-null   int64
 78  R                                                        1136 non-null   int64
 79  Unrated                                                  1136 non-null   int64
 80  Writer_Aaron Sorkin                                      1136 non-null   float64
 81  Writer_Joel Coen                                         1136 non-null   float64
 82  Writer_John Logan                                        1136 non-null   float64
 83  Writer_Lawrence Kasdan                                   1136 non-null   float64
 84  Writer_Paul Thomas Anderson                              1136 non-null   float64
 85  Writer_Pedro Almodóvar                                   1136 non-null   float64
 86  Writer_Quentin Tarantino                                 1136 non-null   float64
 87  Writer_Woody Allen                                       1136 non-null   float64
dtypes: float64(73), int64(15)
memory usage: 781.1 KB

## Split into test sets

In [8]:
X = oscars_data.drop(columns=['metacritic score'])
y = oscars_data['metacritic score']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=27)

In [10]:
X_train.describe()

,Unnamed: 0,runtime (mins),budget,Total_Noms,Director_Avg_Score,Total_Director_Movies,Lead_Actor_Avg_Score,Total_Movies_Lead_Actor,Avg_Rating_by_Genre,Buena Vista Pictures,...,R,Unrated,Writer_Aaron Sorkin,Writer_Joel Coen,Writer_John Logan,Writer_Lawrence Kasdan,Writer_Paul Thomas Anderson,Writer_Pedro Almodóvar,Writer_Quentin Tarantino,Writer_Woody Allen
count,908.000000,908.000000,9.080000e+02,908.000000,908.000000,908.000000,908.000000,908.000000,908.000000,908.000000,...,908.000000,908.000000,908.000000,908.000000,908.000000,908.000000,908.000000,908.000000,908.000000,908.000000
mean,577.232379,120.633260,4.079082e+07,2.889868,71.654360,3.680617,71.625092,3.460352,72.008471,0.039648,...,0.471366,0.014317,0.006608,0.009912,0.002203,0.005507,0.004405,0.005507,0.006608,0.012115
std,328.623641,22.232035,5.078711e+07,2.632799,11.656586,3.779679,11.070046,3.615411,5.425149,0.195237,...,0.499455,0.118860,0.081065,0.099118,0.046906,0.074043,0.066262,0.074043,0.081065,0.109458
min,0.000000,70.000000,0.000000e+00,1.000000,16.000000,1.000000,28.000000,1.000000,38.500000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,297.000000,105.000000,1.000000e+07,1.000000,65.333333,1.000000,65.187500,1.000000,70.200000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,583.000000,118.000000,2.300000e+07,2.000000,73.333333,2.000000,72.666667,2.000000,73.604651,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,862.250000,132.000000,5.000000e+07,4.000000,79.083333,4.000000,78.625000,4.000000,75.185185,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1135.000000,224.000000,3.210000e+08,14.000000,100.000000,20.000000,100.000000,19.000000,91.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
X_test.describe()

,Unnamed: 0,runtime (mins),budget,Total_Noms,Director_Avg_Score,Total_Director_Movies,Lead_Actor_Avg_Score,Total_Movies_Lead_Actor,Avg_Rating_by_Genre,Buena Vista Pictures,...,R,Unrated,Writer_Aaron Sorkin,Writer_Joel Coen,Writer_John Logan,Writer_Lawrence Kasdan,Writer_Paul Thomas Anderson,Writer_Pedro Almodóvar,Writer_Quentin Tarantino,Writer_Woody Allen
count,228.000000,228.000000,2.280000e+02,228.000000,228.000000,228.000000,228.000000,228.000000,228.000000,228.000000,...,228.000000,228.000000,228.0,228.0,228.000000,228.000000,228.000000,228.0,228.0,228.000000
mean,528.741228,117.640351,3.826230e+07,3.092105,73.793162,3.324561,73.909723,3.859649,72.382933,0.035088,...,0.464912,0.008772,0.0,0.0,0.013158,0.008772,0.004386,0.0,0.0,0.004386
std,323.719039,19.950656,4.801554e+07,2.952685,10.346097,3.393426,9.595530,3.679631,5.263883,0.184406,...,0.499865,0.093452,0.0,0.0,0.114201,0.093452,0.066227,0.0,0.0,0.066227
min,2.000000,75.000000,0.000000e+00,1.000000,39.000000,1.000000,38.000000,1.000000,40.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
25%,245.500000,102.000000,7.875000e+06,1.000000,68.750000,1.000000,68.000000,1.000000,70.428571,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
50%,498.500000,116.000000,2.225000e+07,2.000000,74.750000,2.000000,74.562500,2.000000,73.604651,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
75%,822.250000,130.000000,4.725000e+07,4.000000,80.125000,4.000000,80.000000,6.000000,75.185185,0.000000,...,1.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
max,1134.000000,188.000000,3.000000e+08,16.000000,93.000000,20.000000,94.000000,19.000000,91.000000,1.000000,...,1.000000,1.000000,0.0,0.0,1.000000,1.000000,1.000000,0.0,0.0,1.000000

## Scale Numerical Features

In [12]:
X_train_copy = X_train.copy()
X_test_copy = X_test.copy()

In [14]:
scale = StandardScaler().fit(X_train_copy[['budget']])
X_train_copy['budget'] = scale.transform(X_train_copy[['budget']])
X_test_copy['budget'] = scale.transform(X_test_copy[['budget']])

## Do a simple linear regression model on data

In [24]:
lm = LinearRegression()
lm.fit(X_train_copy,y_train)

LinearRegression()

In [25]:
lm.predict(X_train_copy)

array([ 72.7483125 ,  43.36264724,  76.65974212,  73.67734437,
        70.3687361 ,  85.78563515,  69.61835946,  76.17795027,
        73.36011649,  74.01286998,  61.99907409,  78.69886948,
        86.70120607,  83.7145522 ,  68.63322316,  84.17973443,
        64.74489846,  86.11011735,  87.06838223,  78.91541093,
        78.18474523,  78.12426714,  61.49539805,  82.0768134 ,
        71.16014599,  90.82716232,  81.88329461,  73.05742611,
        67.88903039,  71.68674478,  76.44756432, 102.78375057,
        60.10281587,  86.94761641,  74.28329199,  50.03626773,
        67.80910724,  81.39476284,  55.16169567,  69.12605625,
        53.89944708,  64.54144797,  60.15282655,  69.92273056,
        94.91885586,  77.38084703,  61.17447695,  72.77447293,
        60.10461218,  77.17553588,  63.32026945,  77.54656899,
        83.40434733,  71.96058842,  83.07238206,  86.31938531,
        72.36207292,  63.32680803,  97.73344299,  39.51834074,
        74.82216866,  86.46067631,  73.3635161 ,  62.84178588,
        94.8203667 ,  65.01667677,  69.69411083,  80.84986843,
        77.78360567,  85.58944459,  85.41501754,  74.67599272,
        51.04707015,  84.62710758,  95.11552093,  36.63084464,
        78.77343476,  62.19803551,  76.24272346,  80.50455167,
        52.92642972,  73.46453489,  70.95150174,  70.60905147,
        69.10670874,  69.29025543,  90.47153603,  53.26789705,
        81.05441484,  71.70098242,  88.42921664,  74.65744042,
        74.7679626 ,  65.11550031,  55.15584212,  68.53583952,
        80.97717089,  30.47850008,  71.7658364 ,  71.37249268,
        60.89953604,  69.5993214 ,  63.52587845,  80.13630381,
        83.42162448,  89.06400091,  71.80517671,  75.27267796,
        79.73594833,  63.08330953,  88.76182603,  77.31368393,
        75.7137008 ,  39.79411478,  75.52261778,  77.2185571 ,
        43.87523533,  66.41077477,  56.03412884,  64.27759414,
        52.54533481,  90.52423308,  70.89776225,  68.47722803,
        64.16817692,  74.54559258,  84.80899468,  59.03359603,
        79.50126673,  80.68659581,  81.85476387,  70.31804975,
        47.2540838 ,  77.05691023,  73.48580853,  94.15447006,
        83.02258812,  54.22992933,  72.78995945,  87.68658427,
        63.88409174,  50.90931485,  87.86663521,  52.80681373,
        86.59819472,  48.06506712,  63.92298429,  83.31053642,
        63.69535063,  66.3632182 ,  59.18024298,  32.8901588 ,
        65.4615043 ,  68.01258113,  78.96638421,  88.24687188,
        92.91063711,  78.11044186,  61.37202642,  76.54977426,
        56.83487744,  60.42986113,  72.70835771,  58.93831095,
        71.22487489,  75.39435862,  67.1521299 ,  88.77636391,
        91.09399449,  66.68137019,  72.13503212,  62.08489775,
        78.65682538,  75.04337699,  72.78606829,  80.87867791,
        76.05131213,  73.63994112,  89.21183648,  82.08277504,
        69.81524664,  74.79048509,  80.30583947,  70.15574235,
        63.53424116,  73.22292093,  75.63364289,  71.24169761,
        88.29559879,  67.04348282,  50.76334897,  67.67203014,
        82.02754215,  58.76161584,  71.94745485,  79.63286888,
        75.47443553,  55.78581054,  76.35357202,  80.55523099,
        94.76103688,  83.37076113,  76.00623749,  73.16943737,
        64.86059626,  52.65465144,  57.46699941,  90.11337477,
        80.98227046,  69.71735722,  66.20068157,  48.36836186,
        73.05909782,  71.96460809,  79.4963575 ,  81.43265095,
        59.89822442,  66.27285716,  65.83701236,  81.16875956,
        60.79716623,  55.42052959,  60.63588025,  88.44117478,
        73.93511725,  62.44320212,  88.62553076,  69.33834275,
        66.50079147,  59.8400577 ,  76.87840051,  64.13621983,
        68.33030348,  66.69075469,  53.7069    ,  78.58514458,
        73.45870366,  77.49546426,  72.4004356 ,  96.17889088,
        67.89190759,  61.45058482,  82.9305081 ,  38.54807202,
        83.69738815,  69.24717405,  58.56193853,  66.72419826,
        80.7178521 ,  48.34811108,  79.85118199,  66.99869358,
        79.42360043,  90.50147632,  69.17968627,  80.9514451 ,
        76.64357888,  58.30742628,  62.0955166 ,  74.09466368,
        71.90633877,  86.93092523,  95.07756208,  80.65037104,
        76.27805761,  62.93321268,  53.7233109 ,  72.22496924,
        70.80710123,  73.58516081,  74.5400887 ,  75.5194914 ,
        81.20719003,  48.93186569,  81.72569247,  74.38754961,
        66.84298353,  73.35058825,  38.66698229,  48.93402216,
        77.80409416,  24.36234879,  77.13953603,  55.9995524 ,
        94.44368604,  73.31866582,  55.57485535,  90.17054082,
        86.8873446 ,  68.10735563,  71.41109156,  76.99824625,
        85.77693116,  76.64058626,  86.85140908,  69.94348407,
        55.23268935,  69.47698428,  58.76007697,  71.36973113,
        97.46417404,  53.21154441,  28.72856726,  52.93358473,
        73.90295909,  82.03216318,  62.07269607,  67.64670969,
        66.27479018,  75.26453186,  65.29707846,  80.48947607,
        67.56277471,  63.10618996,  82.91521196,  80.29052426,
        77.87964842,  82.4342705 ,  94.28242363,  73.46372283,
        57.14754679,  90.36549248,  75.3090015 ,  66.07084487,
        76.05673917,  78.93177711,  70.64892856,  66.3439803 ,
        69.52615366,  79.00933974,  71.17984946,  79.75001894,
        85.36535498,  82.71239978,  83.35796534,  52.97562784,
        61.33585111,  69.17761993,  35.85114655,  85.81887411,
        72.06022303,  67.56301479,  88.95754745,  71.77893035,
        44.92226932,  83.15907449,  73.98409147,  74.00761389,
        53.58982201,  63.43051143,  81.97751954,  86.97677133,
        87.15328508,  78.84152761,  57.31895632,  84.62408739,
        86.13844064,  73.11477058,  69.20845574,  84.00979006,
        87.58367299,  56.33874997,  93.36579156,  87.4426866 ,
        88.34976351,  51.92036041,  70.56873274,  74.79791952,
        68.91410773,  87.14189217,  77.51938683,  66.88942571,
        69.45613897,  85.90493029,  61.33753651,  57.71021929,
        84.95468667,  64.75980562,  72.7766985 ,  91.21819934,
        66.50819134,  62.84038039,  78.52284762,  65.68944813,
        89.52482099,  77.63560289,  68.28040221,  75.67660156,
        72.83124184,  72.64787787,  50.30968948,  83.30152651,
        56.26625901,  73.49797105,  81.40992857,  31.87061302,
        63.77681595,  80.62975462,  87.87210434,  80.13234168,
        77.68486201,  71.19051023,  78.65016794,  89.99688099,
        55.90648677,  80.64789237,  65.40965263,  58.18362377,
        50.95438993,  67.63958835,  76.0380038 ,  72.32907999,
        81.29983645,  63.88772801,  74.65717443,  84.70633232,
        57.93644376,  60.89220453,  67.2730905 ,  53.38284619,
        68.32285881,  89.98303992,  66.98402613,  78.74258685,
        86.19483936,  84.45763596,  70.43309603,  72.08297963,
        67.41530132,  90.78718284,  50.89083404,  59.17521599,
        71.33594761,  61.24025636,  51.20534981,  97.73166367,
        81.49753151,  51.93698025,  68.11587292,  71.70602255,
        79.19505674,  57.85239805,  63.81247213,  94.15371813,
        80.4910449 ,  72.0492281 ,  82.19107613,  68.71067669,
        67.45602629,  87.08223373,  67.58186582,  56.67524545,
        44.70501507,  60.23225326,  75.62961697,  74.5374887 ,
        78.63824368,  72.86490048,  67.3030336 ,  89.8143703 ,
        65.10003584,  63.37487784,  81.95604502,  64.54038427,
        70.43507117,  55.44739488,  69.31694352,  76.78130218,
        67.38812579,  73.95017789,  79.53525514,  56.13267879,
        74.59394504,  82.53078652,  91.95181924,  76.34313348,
        72.80844906,  69.83836709,  70.19639045,  68.4115618 ,
        84.97978164,  69.72752118,  80.3571145 ,  90.49922911,
        85.5760404 ,  65.45620822,  64.19366455,  65.17279633,
        72.79614661,  49.45673728,  74.81527069,  78.60485696,
        81.20200408,  83.37257284,  80.82353032,  44.87181545,
        82.53239718,  86.7570823 ,  60.50966436,  72.71644592,
        68.69750504,  50.43675809,  53.15683234,  65.8991746 ,
        68.63307617,  76.11709977,  68.05898739,  73.1890528 ,
        85.45615584,  65.77140361,  64.4520462 ,  80.55840585,
        85.97826506,  66.22253704,  58.99342667,  60.58563666,
        68.06580896,  71.02100857,  82.24404546,  79.15271198,
        62.52848344,  75.42400099,  88.45180445,  82.00814182,
        75.72734518,  82.19801142,  75.9663086 ,  73.80939648,
        96.69307332,  69.12888049, 101.72576697,  83.78695062,
        81.81793532,  64.98826969,  73.84342636,  80.5806014 ,
        73.98789356,  86.59873877,  58.54929653,  71.45280301,
        51.61405301,  71.18097528,  63.54952805,  68.51831964,
        68.17599293,  79.16913169,  74.31942301,  83.11411937,
        57.50227351,  44.23058161,  84.96564036,  76.02440571,
        82.06891463,  78.13798549,  56.8738674 ,  73.54890667,
        87.09925579,  65.9738909 ,  82.8437167 ,  62.43767031,
        69.38713148,  26.92173072,  71.28989811,  40.73312344,
        91.45098644,  78.12307939,  65.694635  ,  85.68601572,
        69.87050968,  66.52311319,  84.56253309,  81.62251646,
        83.42413534,  72.03677241,  98.53310112,  66.80288704,
        61.37859281,  55.21539515,  74.27629325,  78.97492608,
        68.67820552,  80.46296231,  66.2638462 ,  64.63642853,
        92.44979213,  65.21578107,  62.69837194,  72.54543758,
        67.21492596,  71.56133585,  51.70076122,  79.77814302,
        67.43097783,  57.40914549,  66.60533603,  51.39496011,
        72.8311989 ,  64.66822305,  91.93989764,  73.79262513,
        60.89856627,  83.16712881,  68.396873  ,  64.36439365,
        84.86871125,  69.13165607,  66.99267279,  76.80709187,
        72.38331389,  84.25956008,  51.84797492,  72.15222046,
        75.1568908 ,  84.29062866,  77.05953135,  58.28930195,
        74.68308099,  79.42329493,  40.50747012,  69.60763736,
        72.67185628,  87.25600346,  70.43514506, 102.60592487,
        73.76406793,  95.30606021,  67.43603139,  74.64670945,
        75.93884321,  82.48951853,  35.70823771,  67.08904981,
        43.95119659,  73.56147912,  71.33671966,  70.81892457,
        44.2464811 ,  79.2313458 ,  67.20581544,  61.91927536,
        68.58139754,  51.33793434,  77.88849354,  85.37123382,
        72.50749538,  88.56863589,  69.767276  ,  66.10809085,
        64.07813114,  84.55441205,  78.67902566,  81.80847729,
        73.6554358 ,  75.13128875,  82.20654378,  42.46155345,
        72.16194875,  61.9056651 ,  91.        ,  64.62189155,
        77.05418042,  62.01435734,  72.58184364,  74.71419873,
        73.87472851,  43.06603788,  79.46954351,  64.40829702,
        76.06001014,  89.23279988,  59.72304293,  74.27009216,
        89.85483684,  77.59677789, 102.16824056,  79.03522718,
        73.53945907,  88.92646306,  66.12986336,  58.43827433,
        59.26600098,  74.15928264,  67.57619941,  81.18255557,
        73.50025976,  59.43604804,  72.73610366,  73.98515625,
        72.5367234 ,  72.40104628,  73.51201852,  67.7748101 ,
        49.92377082,  77.5408402 ,  63.88910859,  32.07319488,
        58.70739218,  93.32817278,  84.5028482 ,  78.26039191,
        69.69826291, 103.77881924,  66.26344461,  61.85179442,
        59.84637764,  48.30789542,  79.59014312,  52.08615066,
        81.21107711,  77.59428677,  78.28981745,  79.85000893,
        96.54359539,  91.872217  ,  71.00696463,  40.58387692,
        89.27411504,  68.74103295,  89.55427124,  70.45321982,
        72.53671907,  76.92945858,  56.41474884,  59.88160015,
        74.24845137,  80.606328  ,  73.21225382,  69.14269742,
        69.36277016,  74.47280712,  49.02614127,  75.34652654,
        68.04750782,  78.31765008,  80.44267757,  39.10668122,
        69.00447796,  79.28487736,  72.07384254,  92.41633785,
        66.2510945 ,  69.15906508,  71.72343548,  79.6883292 ,
        67.51437923,  82.81427826,  92.66493009,  69.65160407,
        58.95771884,  70.56620242,  91.73706821,  72.78986292,
        71.06483979,  62.73005383,  66.03185088,  67.09488494,
        76.47403885,  74.60095281,  83.645055  ,  76.25663438,
        50.71716586,  70.21877574,  52.3881065 ,  78.72816391,
        78.53260097,  65.23583499,  82.48195622,  48.53557966,
        59.9767037 ,  66.80826453,  66.26583908,  84.5967821 ,
        51.35376749,  60.71593532,  43.47145361,  78.70859093,
        76.00335242,  66.26338255,  74.25986784,  75.58095248,
       101.06933027,  73.64802687,  63.35215297,  52.21009846,
        83.16991532,  57.7081568 ,  69.92341048,  62.619952  ,
        62.3122704 ,  68.4287002 ,  40.50746886,  74.09249657,
        66.9666268 ,  74.26767419,  65.27365856,  60.87475753,
        72.97167286,  72.7590847 ,  58.38128016,  84.5393683 ,
        95.00754377,  68.54936331,  88.80343852,  54.45248891,
        73.51856043,  89.96848127,  67.1382527 ,  75.64704438,
        88.55483812,  76.10248053,  79.59779209,  59.65672867,
        61.34075782,  58.13445282,  73.02047153,  72.89096364,
        70.10749341,  71.61049482,  52.94596214,  52.58413484,
        72.60832863,  69.67251976,  56.82437363,  70.36194119,
        76.44247727,  59.90581176, 100.01843765,  73.21001359,
        79.37928372,  77.34492438,  68.02419649,  50.7289711 ,
        89.70973518,  69.47634223,  66.00641709,  71.33607319,
        60.78275707,  70.30217858,  70.74396033,  83.71126984,
        73.82619472,  44.43378666,  57.33262604,  88.11249635,
        63.31814472,  93.05924953,  51.81080244,  75.43257427,
        77.36505022,  65.28395604,  73.2826933 ,  72.79372459,
        81.04715249,  55.19992444,  74.22250448,  61.99349611,
        84.8692078 ,  56.6695202 ,  69.98177376,  38.75505809,
        64.62269741,  72.56766598,  84.0121614 ,  71.3383344 ,
        53.04217027,  52.29416471,  63.91594887,  85.56090981,
        75.41742929,  54.38137903,  82.03142406,  76.3462407 ,
        71.52001632,  77.21088063,  55.76895188,  56.54655769,
        62.16926011,  75.92388728,  57.77386692,  61.14854947,
        62.3178904 ,  82.88817041,  52.30680222,  70.27720728,
        78.58031353,  79.49127298,  64.00885412,  31.77461897,
        80.61158343,  48.48424985,  66.63699669,  75.64520802,
        73.64788646,  70.00684958,  65.35272109,  74.58257738,
        76.28580025,  67.76959346,  63.78883006,  64.43637795,
        74.24721677,  79.87501661,  74.8719524 ,  70.7945764 ,
        81.89595685,  61.8927521 ,  63.174368  ,  78.24146318])

array([ 72.74831251,  43.36264724,  76.65974211,  73.67734436,
        70.3687361 ,  85.78563519,  69.61835947,  76.17795027,
        73.36011644,  74.01286996,  61.99907411,  78.69886952,
        86.70120607,  83.71455225,  68.63322297,  84.17973438,
        64.74489833,  86.11011744,  87.06838227,  78.91541093,
        78.18474526,  78.12426717,  61.49539802,  82.0768134 ,
        71.160146  ,  90.82716233,  81.88329462,  73.05742605,
        67.88903041,  71.6867448 ,  76.44756433, 102.78375062,
        60.10281585,  86.94761639,  74.28329195,  50.03626767,
        67.80910726,  81.39476282,  55.16169561,  69.12605619,
        53.89944709,  64.54144794,  60.15282647,  69.92273047,
        94.91885578,  77.38084708,  61.17447687,  72.77447291,
        60.10461225,  77.17553589,  63.3202695 ,  77.54656898,
        83.40434732,  71.96058838,  83.07238206,  86.31938536,
        72.36207291,  63.32680801,  97.73344302,  39.51834069,
        74.82216867,  86.46067628,  73.36351607,  62.84178584,
        94.82036673,  65.01667674,  69.69411081,  80.84986853,
        77.78360569,  85.58944452,  85.41501755,  74.67599266,
        51.04707017,  84.62710753,  95.11552094,  36.63084463,
        78.77343472,  62.19803543,  76.24272341,  80.5045517 ,
        52.92642968,  73.46453481,  70.95150177,  70.60905145,
        69.1067087 ,  69.29025547,  90.47153599,  53.26789706,
        81.05441479,  71.7009824 ,  88.42921662,  74.6574404 ,
        74.76796256,  65.11550026,  55.1558422 ,  68.53583949,
        80.97717085,  30.47850003,  71.76583637,  71.37249271,
        60.89953604,  69.59932135,  63.52587841,  80.13630375,
        83.42162448,  89.06400093,  71.80517672,  75.27267797,
        79.73594856,  63.08330959,  88.76182598,  77.31368397,
        75.71370076,  39.7941148 ,  75.52261777,  77.21855713,
        43.87523528,  66.41077481,  56.03412888,  64.27759408,
        52.54533485,  90.52423311,  70.8977622 ,  68.47722807,
        64.16817696,  74.54559259,  84.80899469,  59.0335961 ,
        79.50126669,  80.6865959 ,  81.85476386,  70.31804973,
        47.25408379,  77.05691024,  73.48580848,  94.15447002,
        83.02258804,  54.22992932,  72.78995944,  87.68658431,
        63.88409173,  50.90931488,  87.86663524,  52.80681376,
        86.59819472,  48.0650671 ,  63.92298423,  83.31053648,
        63.69535061,  66.36321838,  59.18024295,  32.89015878,
        65.46150426,  68.01258108,  78.96638426,  88.24687195,
        92.91063709,  78.11044185,  61.3720264 ,  76.54977434,
        56.83487738,  60.42986119,  72.70835765,  58.93831091,
        71.22487486,  75.39435859,  67.1521299 ,  88.77636404,
        91.09399453,  66.68137022,  72.13503216,  62.0848977 ,
        78.65682534,  75.04337697,  72.78606834,  80.87867792,
        76.05131221,  73.63994113,  89.21183649,  82.08277503,
        69.8152466 ,  74.79048517,  80.30583947,  70.15574238,
        63.5342412 ,  73.22292089,  75.63364289,  71.24169765,
        88.29559884,  67.04348281,  50.76334901,  67.67203009,
        82.02754217,  58.76161587,  71.94745488,  79.63286893,
        75.47443555,  55.78581057,  76.35357208,  80.55523098,
        94.76103691,  83.37076118,  76.00623751,  73.16943734,
        64.86059627,  52.65465144,  57.46699946,  90.11337476,
        80.98227044,  69.71735718,  66.20068162,  48.36836187,
        73.05909781,  71.96460815,  79.49635743,  81.432651  ,
        59.89822441,  66.27285717,  65.8370124 ,  81.16875962,
        60.79716624,  55.42052961,  60.63588024,  88.44117482,
        73.93511728,  62.4432021 ,  88.62553072,  69.33834275,
        66.50079147,  59.84005768,  76.87840045,  64.13621992,
        68.33030347,  66.69075464,  53.70689992,  78.58514454,
        73.45870361,  77.49546426,  72.40043559,  96.1788909 ,
        67.89190762,  61.4505848 ,  82.93050803,  38.54807199,
        83.69738815,  69.24717403,  58.56193855,  66.72419827,
        80.71785209,  48.34811114,  79.851182  ,  66.99869355,
        79.42360044,  90.50147635,  69.17968623,  80.95144509,
        76.64357894,  58.30742626,  62.09551659,  74.09466368,
        71.90633872,  86.93092521,  95.0775621 ,  80.65037104,
        76.27805763,  62.93321268,  53.72331082,  72.22496931,
        70.80710116,  73.58516078,  74.54008867,  75.51949139,
        81.20718997,  48.93186572,  81.72569244,  74.38754959,
        66.84298345,  73.35058829,  38.66698233,  48.93402217,
        77.80409421,  24.36234878,  77.13953595,  55.99955239,
        94.44368606,  73.31866581,  55.57485534,  90.17054083,
        86.88734461,  68.10735559,  71.41109162,  76.99824622,
        85.7769312 ,  76.64058632,  86.85140909,  69.94348401,
        55.23268936,  69.47698426,  58.76007696,  71.36973113,
        97.46417406,  53.21154443,  28.72856729,  52.93358469,
        73.90295915,  82.03216317,  62.07269595,  67.64670975,
        66.27479019,  75.26453188,  65.29707858,  80.48947615,
        67.56277468,  63.10618993,  82.9152119 ,  80.29052421,
        77.87964846,  82.43427051,  94.28242363,  73.46372278,
        57.14754691,  90.36549244,  75.30900147,  66.07084486,
        76.05673924,  78.93177711,  70.64892857,  66.34398031,
        69.52615365,  79.00933974,  71.17984947,  79.75001895,
        85.36535501,  82.7123997 ,  83.35796535,  52.97562779,
        61.33585107,  69.17761987,  35.8511465 ,  85.81887412,
        72.06022303,  67.56301477,  88.95754739,  71.7789303 ,
        44.92226929,  83.1590745 ,  73.98409144,  74.0076139 ,
        53.58982201,  63.43051144,  81.97751954,  86.97677129,
        87.15328504,  78.84152759,  57.31895629,  84.62408741,
        86.1384406 ,  73.11477056,  69.20845573,  84.0097901 ,
        87.58367304,  56.33874995,  93.36579166,  87.44268656,
        88.34976354,  51.92036045,  70.56873273,  74.79791953,
        68.9141077 ,  87.14189217,  77.5193869 ,  66.88942575,
        69.45613902,  85.90493032,  61.33753653,  57.71021932,
        84.95468668,  64.75980566,  72.77669849,  91.21819938,
        66.50819135,  62.8403804 ,  78.52284768,  65.68944812,
        89.52482098,  77.63560291,  68.28040226,  75.67660159,
        72.83124176,  72.64787777,  50.30968944,  83.30152645,
        56.26625903,  73.49797107,  81.40992858,  31.87061299,
        63.77681592,  80.62975464,  87.87210437,  80.13234173,
        77.68486196,  71.19051023,  78.65016795,  89.99688095,
        55.90648682,  80.64789234,  65.40965262,  58.18362379,
        50.95438987,  67.63958839,  76.03800381,  72.32907996,
        81.29983647,  63.88772798,  74.65717445,  84.70633222,
        57.93644375,  60.89220454,  67.27309048,  53.38284616,
        68.32285891,  89.98303993,  66.98402618,  78.74258689,
        86.19483939,  84.45763592,  70.43309606,  72.08297961,
        67.41530128,  90.78718284,  50.89083402,  59.17521595,
        71.33594765,  61.24025631,  51.20534982,  97.73166364,
        81.49753153,  51.93698028,  68.11587294,  71.70602261,
        79.19505668,  57.85239801,  63.81247207,  94.15371818,
        80.49104491,  72.0492281 ,  82.19107609,  68.7106767 ,
        67.45602628,  87.08223371,  67.58186586,  56.67524542,
        44.70501509,  60.23225334,  75.62961694,  74.53748866,
        78.63824369,  72.86490055,  67.30303363,  89.81437028,
        65.10003586,  63.37487789,  81.95604506,  64.54038425,
        70.43507119,  55.44739479,  69.31694351,  76.78130222,
        67.38812575,  73.95017789,  79.53525526,  56.13267878,
        74.59394502,  82.53078656,  91.9518193 ,  76.3431335 ,
        72.80844902,  69.83836715,  70.19639048,  68.41156181,
        84.97978164,  69.72752114,  80.35711455,  90.49922914,
        85.57604029,  65.45620841,  64.19366458,  65.17279633,
        72.79614656,  49.45673728,  74.81527067,  78.60485704,
        81.20200402,  83.37257281,  80.82353034,  44.87181543,
        82.53239721,  86.75708231,  60.50966435,  72.71644591,
        68.69750507,  50.43675809,  53.15683239,  65.89917461,
        68.63307616,  76.11709967,  68.05898742,  73.18905285,
        85.45615584,  65.77140361,  64.45204615,  80.55840587,
        85.97826513,  66.22253703,  58.9934267 ,  60.58563668,
        68.06580887,  71.02100858,  82.2440454 ,  79.1527119 ,
        62.52848345,  75.42400102,  88.45180445,  82.00814181,
        75.72734524,  82.19801146,  75.9663086 ,  73.80939641,
        96.69307333,  69.12888053, 101.72576698,  83.78695065,
        81.81793528,  64.98826969,  73.84342632,  80.58060135,
        73.98789354,  86.59873883,  58.54929652,  71.45280306,
        51.61405299,  71.18097528,  63.54952804,  68.51831962,
        68.17599282,  79.16913172,  74.31942302,  83.11411941,
        57.50227346,  44.23058159,  84.96564033,  76.02440564,
        82.06891456,  78.13798548,  56.87386741,  73.54890674,
        87.09925589,  65.97389094,  82.84371677,  62.43767033,
        69.3871315 ,  26.92173071,  71.28989812,  40.73312339,
        91.45098644,  78.12307935,  65.69463498,  85.68601574,
        69.87050969,  66.52311324,  84.56253308,  81.6225165 ,
        83.42413531,  72.03677243,  98.53310111,  66.80288709,
        61.37859281,  55.21539518,  74.27629331,  78.97492602,
        68.67820554,  80.46296226,  66.2638462 ,  64.63642855,
        92.44979218,  65.21578106,  62.69837194,  72.54543755,
        67.21492595,  71.56133586,  51.7007612 ,  79.77814304,
        67.43097785,  57.40914549,  66.60533606,  51.39496015,
        72.83119882,  64.66822312,  91.93989765,  73.79262513,
        60.8985663 ,  83.16712877,  68.39687295,  64.36439372,
        84.86871137,  69.13165603,  66.99267278,  76.80709189,
        72.38331389,  84.25956012,  51.84797492,  72.15222039,
        75.15689079,  84.29062863,  77.05953137,  58.28930192,
        74.68308103,  79.42329493,  40.5074701 ,  69.6076373 ,
        72.67185623,  87.25600345,  70.43514505, 102.6059249 ,
        73.76406796,  95.30606021,  67.43603133,  74.64670943,
        75.93884321,  82.48951856,  35.7082377 ,  67.0890498 ,
        43.95119664,  73.56147911,  71.33671963,  70.81892457,
        44.24648108,  79.23134588,  67.20581553,  61.91927538,
        68.58139745,  51.33793435,  77.88849355,  85.3712338 ,
        72.50749542,  88.56863584,  69.76727599,  66.10809085,
        64.07813114,  84.55441205,  78.67902567,  81.80847735,
        73.65543572,  75.13128886,  82.20654373,  42.46155347,
        72.16194874,  61.90566514,  90.99999972,  64.62189154,
        77.0541805 ,  62.01435732,  72.58184366,  74.71419877,
        73.87472857,  43.06603784,  79.4695435 ,  64.40829701,
        76.06001016,  89.23279986,  59.72304286,  74.2700922 ,
        89.85483684,  77.59677788, 102.16824058,  79.03522717,
        73.53945906,  88.92646297,  66.12986337,  58.43827429,
        59.26600103,  74.15928259,  67.57619943,  81.18255558,
        73.5002597 ,  59.43604805,  72.73610366,  73.9851563 ,
        72.53672348,  72.40104627,  73.51201848,  67.77481007,
        49.92377084,  77.54084016,  63.88910867,  32.07319494,
        58.70739212,  93.32817278,  84.5028482 ,  78.26039198,
        69.69826292, 103.77881928,  66.26344465,  61.85179443,
        59.84637764,  48.30789551,  79.59014305,  52.08615068,
        81.21107715,  77.5942868 ,  78.28981744,  79.85000897,
        96.54359541,  91.87221702,  71.00696452,  40.58387692,
        89.27411504,  68.74103298,  89.55427121,  70.45321981,
        72.53671906,  76.92945858,  56.41474883,  59.88160014,
        74.24845134,  80.60632794,  73.21225388,  69.14269741,
        69.36277012,  74.47280716,  49.02614128,  75.34652658,
        68.04750782,  78.31765002,  80.44267755,  39.10668123,
        69.00447796,  79.28487736,  72.07384255,  92.41633792,
        66.25109453,  69.1590651 ,  71.72343549,  79.6883292 ,
        67.51437922,  82.81427831,  92.66493006,  69.65160405,
        58.95771885,  70.56620242,  91.73706829,  72.78986292,
        71.06483977,  62.7300538 ,  66.03185085,  67.09488494,
        76.47403886,  74.60095278,  83.64505498,  76.25663437,
        50.71716589,  70.2187757 ,  52.38810647,  78.72816398,
        78.53260095,  65.235835  ,  82.48195623,  48.53557964,
        59.97670367,  66.80826457,  66.26583911,  84.59678213,
        51.35376751,  60.71593524,  43.47145361,  78.70859091,
        76.00335238,  66.26338254,  74.25986779,  75.5809525 ,
       101.06933029,  73.64802687,  63.35215294,  52.21009848,
        83.16991533,  57.70815684,  69.92341049,  62.61995205,
        62.31227036,  68.42870024,  40.5074689 ,  74.09249661,
        66.96662681,  74.26767421,  65.27365858,  60.87475754,
        72.97167286,  72.75908476,  58.38128012,  84.5393683 ,
        95.00754378,  68.54936335,  88.80343856,  54.4524889 ,
        73.51856049,  89.96848121,  67.13825269,  75.64704434,
        88.55483803,  76.10248055,  79.59779212,  59.65672867,
        61.34075784,  58.13445281,  73.02047153,  72.89096359,
        70.10749346,  71.61049479,  52.94596211,  52.58413483,
        72.60832862,  69.67251972,  56.82437362,  70.36194124,
        76.44247725,  59.90581163, 100.01843766,  73.21001351,
        79.37928372,  77.34492435,  68.02419647,  50.72897115,
        89.70973515,  69.47634225,  66.00641717,  71.33607323,
        60.78275704,  70.30217859,  70.74396029,  83.71126985,
        73.82619475,  44.43378667,  57.33262594,  88.11249633,
        63.31814473,  93.0592495 ,  51.81080245,  75.43257427,
        77.36505025,  65.28395606,  73.28269326,  72.79372462,
        81.04715247,  55.19992449,  74.2225045 ,  61.99349611,
        84.8692078 ,  56.6695201 ,  69.98177374,  38.75505807,
        64.62269741,  72.56766603,  84.01216144,  71.33833439,
        53.04217031,  52.29416472,  63.91594886,  85.56090982,
        75.41742926,  54.38137906,  82.03142408,  76.34624067,
        71.52001637,  77.21088067,  55.76895189,  56.54655764,
        62.16926013,  75.92388731,  57.77386693,  61.14854943,
        62.31789043,  82.88817044,  52.3068023 ,  70.27720721,
        78.5803136 ,  79.491273  ,  64.00885415,  31.77461893,
        80.61158342,  48.48424983,  66.63699669,  75.64520797,
        73.64788635,  70.0068496 ,  65.35272115,  74.5825774 ,
        76.28580029,  67.76959344,  63.78883009,  64.43637796,
        74.24721667,  79.87501659,  74.87195229,  70.79457638,
        81.89595686,  61.89275216,  63.17436801,  78.24146322])

In [26]:
list(zip(oscars_data.drop(columns='metacritic score'),lm.coef_))

[('Unnamed: 0', -0.001214351584881671),
 ('runtime (mins)', -0.012869519134217744),
 ('budget', -1.0492476622985012),
 ('Total_Noms', 1.1159872789960894),
 ('Director_Avg_Score', 0.624649211952596),
 ('Total_Director_Movies', -0.0538893158404182),
 ('Lead_Actor_Avg_Score', 0.4367772345092507),
 ('Total_Movies_Lead_Actor', -0.10468657689819921),
 ('Avg_Rating_by_Genre', 0.13400834367730005),
 ('Buena Vista Pictures', -0.599595044150699),
 ('Columbia Pictures', -0.39806363560522584),
 ('Fox Searchlight Pictures', 0.6057510173401672),
 ('Miramax', -0.836605381813148),
 ('Paramount Pictures', 0.1336079622751971),
 ('Sony Pictures Classics', 0.9957492015920288),
 ('Twentieth Century Fox', 0.9702290386311831),
 ('Universal Pictures', -0.7421316789896383),
 ('Walt Disney Studios Motion Pictures', 1.723090495017947),
 ('Warner Bros.', -0.42468517421763186),
 ('Genre_Action', 4.250454520356497),
 ('Genre_Adventure', 2.1273229861814036),
 ('Genre_Animation', 3.430233409305947),
 ('Genre_Biography', 1.6917006967977888),
 ('Genre_Comedy', 2.44949277343546),
 ('Genre_Crime', 1.455709645250637),
 ('Genre_Documentary', 1.3889555537686338),
 ('Genre_Drama', 0.71440279846686),
 ('Genre_Family', 0.5462860498275393),
 ('Genre_Horror', 1.9575026460389002),
 ('Subgenre_Adventure', -0.17929515556581865),
 ('Subgenre_Comedy', 0.39117716012105563),
 ('Subgenre_Crime', 0.6995273825670834),
 ('Subgenre_Drama', -0.9938892510144438),
 ('Subgenre_Fantasy', -0.08569710517221618),
 ('Subgenre_History', -0.6068507289440952),
 ('Subgenre_Music', 0.4786208618846877),
 ('Subgenre_Mystery', 0.2706773184048131),
 ('Subgenre_Romance', -0.5955455308908917),
 ('Subgenre_Thriller', -0.13571076561222292),
 ('Director_Barry Levinson', -1.6449984593994835),
 ('Director_Clint Eastwood', 0.0883792776417327),
 ('Director_Martin Scorsese', 4.876417475476854),
 ('Director_Ridley Scott', 0.8840987678255946),
 ('Director_Robert Zemeckis', 0.6341127916532807),
 ('Director_Ron Howard', 1.5404152121049548),
 ('Director_Stephen Frears', 0.2240828499146475),
 ('Director_Steven Spielberg', -0.2507598812624158),
 ('Director_Tim Burton', 1.3733350694525592),
 ('Director_Woody Allen', 0.8590596276808731),
 ('Lead_Actor_Brad Pitt', -2.013287687709784),
 ('Lead_Actor_Harrison Ford', -2.4313630853087265),
 ('Lead_Actor_Johnny Depp', 4.016588620426458),
 ('Lead_Actor_Leonardo DiCaprio', -2.607872682613802),
 ('Lead_Actor_Meryl Streep', 0.45669367252280424),
 ('Lead_Actor_Robert De Niro', -4.969662277917236),
 ('Lead_Actor_Robert Downey Jr.', 3.58509363801619),
 ('Lead_Actor_Robin Williams', 5.19394760983913),
 ('Lead_Actor_Tom Cruise', -1.3253706322345995),
 ('Lead_Actor_Tom Hanks', 1.5186721406706043),
 ('Awards_Best Actor in a Leading Role', 0.4620618958433249),
 ('Awards_Best Actor in a Supporting Role', 0.8173970986692397),
 ('Awards_Best Actress in a Leading Role', 0.7577355993178279),
 ('Awards_Best Actress in a Supporting Role', 0.5498016909978277),
 ('Awards_Best Art Direction-Set Decoration', -2.2401620832224656),
 ('Awards_Best Foreign Language Film', 1.067421256270209),
 ('Awards_Best Foreign Language Film of the Year', 0.6842738076152095),
 ('Awards_Best Motion Picture of the Year', -1.715117316861985),
 ('Awards_Best Music, Original Song', -0.18427753291708265),
 ('Awards_Best Performance by an Actress in a Leading Role',
  0.31945149343187407),
 ('Fall', -0.3242945473216343),
 ('Spring', 0.15499840753226124),
 ('Summer', 1.1021071755627294),
 ('Winter', -0.9328110357697756),
 ('G', -0.22780562622663325),
 ('Not Rated', -0.05651547229236509),
 ('PG', -0.07595708896450404),
 ('PG-13', -0.5371136314095133),
 ('R', 0.6506861871874889),
 ('Unrated', 0.24670563170953286),
 ('Writer_Aaron Sorkin', 0.89897520813996),
 ('Writer_Joel Coen', -0.410721034628856),
 ('Writer_John Logan', -6.503469598583603),
 ('Writer_Lawrence Kasdan', 1.5131159232181246),
 ('Writer_Paul Thomas Anderson', 0.9073856761005601),
 ('Writer_Pedro Almodóvar', -0.336048606305273),
 ('Writer_Quentin Tarantino', 0.7177607844131023),
 ('Writer_Woody Allen', 0.8590596276812861)]

In [27]:
lm.intercept_

-16.346822702700464

In [29]:
lm.score(X_train_copy,y_train)

0.8367729252800911

In [31]:
lm.score(X_test_copy,y_test)

0.7612225827533228

In [32]:
from sklearn.model_selection import cross_val_score

cross_val_score(lm, X, y, # estimator, features, target
                cv=5, # number of folds 
                scoring='r2') # scoring metric

array([0.6772543 , 0.68672956, 0.75630393, 0.79836679, 0.80926274])